# Innovation Summit 2026: Form 5500 Exploratory Data Analysis

This is a notebook of exploratory data analysis, made by Corey Michaud, for the Deloitte Innovation Summit 2026 Competition as a part of the Data Atlas team.

## Libraries

In [1]:
# Libraries
import pandas as pd
from innovation_summit.config import COMBINED_DATA_PATH

In [2]:
# Displaying all
pd.set_option("display.max_rows", None)

## Load data

In [3]:
# Loading data
F5500 = pd.read_parquet(COMBINED_DATA_PATH / "F5500.parquet")
SCH_A = pd.read_parquet(COMBINED_DATA_PATH / "SCH_A.parquet")
SCH_C_P1_I2 = pd.read_parquet(COMBINED_DATA_PATH / "SCH_C_P1_I2.parquet")

## Viewing data

In [4]:
# Head of F5500
F5500.head()

,ACK_ID,FORM_PLAN_YEAR_BEGIN_DATE,FORM_TAX_PRD,TYPE_PLAN_ENTITY_CD,TYPE_DFE_PLAN_ENTITY_CD,INITIAL_FILING_IND,AMENDED_IND,FINAL_FILING_IND,SHORT_PLAN_YR_IND,COLLECTIVE_BARGAIN_IND,...,SPONS_MANUAL_SIGNED_DATE,SPONS_MANUAL_SIGNED_NAME,DFE_MANUAL_SIGNED_DATE,DFE_MANUAL_SIGNED_NAME,FORM_YEAR,ADOPTED_PLAN_PERM_SEC_ACT,PARTCP_ACCOUNT_BAL_CNT_BOY,SCH_DCG_ATTACHED_IND,NUM_SCH_DCG_ATTACHED_CNT,SCH_MEP_ATTACHED_IND
0,20200324164957NAL0006771024001,2019-01-01,2019-12-31,2,<NA>,0,0,0,0,0,...,NaN,<NA>,NaN,<NA>,2019,<NA>,<NA>,<NA>,<NA>,<NA>
1,20200324105626NAL0010195186001,1998-01-01,1998-12-31,2,<NA>,0,0,0,0,0,...,NaN,<NA>,NaN,<NA>,2019,<NA>,<NA>,<NA>,<NA>,<NA>
2,20200324105715NAL0010195522001,2019-01-01,2019-12-12,2,<NA>,0,0,1,1,0,...,NaN,<NA>,NaN,<NA>,2019,<NA>,<NA>,<NA>,<NA>,<NA>
3,20200324105729NAL0006723568001,1997-01-01,1997-12-31,2,<NA>,0,0,0,0,0,...,NaN,<NA>,NaN,<NA>,2019,<NA>,<NA>,<NA>,<NA>,<NA>
4,20200324105821NAL0006724848001,1996-01-01,1996-12-31,2,<NA>,1,0,0,0,0,...,NaN,<NA>,NaN,<NA>,2019,<NA>,<NA>,<NA>,<NA>,<NA>

In [5]:
# Head of SCH_A
SCH_A.head()

,ACK_ID,FORM_ID,SCH_A_PLAN_YEAR_BEGIN_DATE,SCH_A_PLAN_YEAR_END_DATE,SCH_A_PLAN_NUM,SCH_A_EIN,INS_CARRIER_NAME,INS_CARRIER_EIN,INS_CARRIER_NAIC_CODE,INS_CONTRACT_NUM,...,WLFR_HELD_BNFTS_AMT,WLFR_CLAIMS_RESERVE_AMT,WLFR_OTH_RESERVE_AMT,WLFR_DIVNDS_DUE_AMT,WLFR_TOT_CHARGES_PAID_AMT,WLFR_ACQUIS_COST_AMT,WLFR_ACQUIS_COST_TEXT,INS_FAIL_PROVIDE_INFO_IND,INS_FAIL_PROVIDE_INFO_TEXT,FORM_YEAR
0,20200407140313NAL0005903843001,1.0,2019-01-01,2019-12-31,001,746141016,AMERITAS LIFE INSURANCE CO.,470098400,61301,E23 0351,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2019
1,20200408103626NAL0010330753001,1.0,2013-11-01,2014-10-31,502,620648833,USABLE LIFE,710505232,94358,50003755,...,<NA>,<NA>,<NA>,<NA>,21442.0,<NA>,<NA>,2,<NA>,2019
2,20200408103626NAL0010330753001,2.0,2013-11-01,2014-10-31,502,620648833,USABLE LIFE,710505232,94358,50003755,...,<NA>,<NA>,<NA>,<NA>,11101.0,<NA>,<NA>,2,<NA>,2019
3,20200408103709NAL0014724896001,1.0,2014-11-01,2015-10-31,502,620648833,USABLE LIFE,710505232,94358,50003755,...,<NA>,<NA>,<NA>,<NA>,21448.0,<NA>,<NA>,2,<NA>,2019
4,20200408103709NAL0014724896001,2.0,2014-11-01,2015-10-31,502,620648833,USABLE LIFE,710505232,94358,50003755,...,<NA>,<NA>,<NA>,<NA>,11845.0,<NA>,<NA>,2,<NA>,2019

In [6]:
# Head of SCH_C_P1_I2
SCH_C_P1_I2.head()

,ACK_ID,ROW_ORDER,PROVIDER_OTHER_NAME,PROVIDER_OTHER_EIN,PROVIDER_OTHER_US_ADDRESS1,PROVIDER_OTHER_US_ADDRESS2,PROVIDER_OTHER_US_CITY,PROVIDER_OTHER_US_STATE,PROVIDER_OTHER_US_ZIP,PROV_OTHER_FOREIGN_ADDRESS1,...,PROV_OTHER_FOREIGN_CNTRY,PROV_OTHER_FOREIGN_POSTAL_CD,PROVIDER_OTHER_SRVC_CODES,PROVIDER_OTHER_RELATION,PROVIDER_OTHER_DIRECT_COMP_AMT,PROV_OTHER_INDIRECT_COMP_IND,PROV_OTHER_ELIG_IND_COMP_IND,PROV_OTHER_TOT_IND_COMP_AMT,PROVIDER_OTHER_AMT_FORMULA_IND,FORM_YEAR
0,20200720121624NAL0000978001001,4.0,HUB INTERNATIONAL OF ILLINOIS LTD,<NA>,55 E JACKSON BLVD FL 12,<NA>,CHICAGO,IL,60604,<NA>,...,<NA>,<NA>,<NA>,BROKER,0.0,1,2,8160.0,2,2019
1,20200720121624NAL0000978001001,5.0,CAREBRIDGE CORPORATION,232614764,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,CONTRACT ADMINISTRATORS,8056.0,2,<NA>,<NA>,<NA>,2019
2,20200720121725NAL0001062131001,1.0,GREAT-WEST LIFE & ANNUITY INSURANCE,840467907,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,RECORDKEEPER,29113.0,1,1,0.0,1,2019
3,20200720122157NAL0001065651001,1.0,JOHN HANCOCK LIFE INSURANCE COMPANY,010233346,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,RECORDKEEPER,992.0,1,1,0.0,1,2019
4,20200720122209NAL0001706226003,1.0,"UMR, INC.",391995276,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,CLAIMS PROCESSING,765329.0,1,2,11943.0,2,2019

## Shape of data

In [7]:
# Shape
print(f"F5500 has {F5500.shape[0]} rows & {F5500.shape[1]} columns")
print(f"SCH_A has {SCH_A.shape[0]} rows & {SCH_A.shape[1]} columns")
print(f"SCH_C_P1_I2 has {SCH_C_P1_I2.shape[0]} rows & {SCH_C_P1_I2.shape[1]} columns")

F5500 has 1440843 rows & 141 columns
SCH_A has 2013921 rows & 91 columns
SCH_C_P1_I2 has 1691315 rows & 23 columns

## Data types

In [8]:
# Data type counts
print(f"F5500 has the dtypes counts of:\n{F5500.dtypes.value_counts()}\n")
print(f"SCH_A has the dtypes counts of:\n{SCH_A.dtypes.value_counts()}\n")
print(f"SCH_C_P1_I2 has the dtypes counts of:\n{SCH_C_P1_I2.dtypes.value_counts()}\n")

F5500 has the dtypes counts of:
string            118
Float64            13
str                 7
datetime64[us]      3
Name: count, dtype: int64

SCH_A has the dtypes counts of:
Float64           45
string            41
datetime64[us]     4
str                1
Name: count, dtype: int64

SCH_C_P1_I2 has the dtypes counts of:
string     19
Float64     3
str         1
Name: count, dtype: int64

## Any missing data?

In [9]:
# No missing data
print(f"F5500 columns with no missing data:\n{F5500.isna().sum()[F5500.isna().sum() == 0]}\n")
print(f"SCH_A columns with no missing data:\n{SCH_A.isna().sum()[SCH_A.isna().sum() == 0]}\n")
print(f"SCH_C_P1_I2 columns with no missing data:\n{SCH_C_P1_I2.isna().sum()[SCH_C_P1_I2.isna().sum() == 0]}")

F5500 columns with no missing data:
ACK_ID                       0
FORM_PLAN_YEAR_BEGIN_DATE    0
FORM_TAX_PRD                 0
SPONS_DFE_PN                 0
SPONSOR_DFE_NAME             0
SPONS_DFE_EIN                0
FILING_STATUS                0
DATE_RECEIVED                0
FORM_YEAR                    0
dtype: int64

SCH_A columns with no missing data:
ACK_ID                        0
FORM_ID                       0
SCH_A_PLAN_YEAR_BEGIN_DATE    0
SCH_A_PLAN_YEAR_END_DATE      0
SCH_A_PLAN_NUM                0
SCH_A_EIN                     0
FORM_YEAR                     0
dtype: int64

SCH_C_P1_I2 columns with no missing data:
ACK_ID       0
ROW_ORDER    0
FORM_YEAR    0
dtype: int64

In [10]:
# F5500 missing data
pd.DataFrame({
    "missing_count": F5500.isna().sum(),
    "missing_percent": F5500.isna().mean().mul(100)
}).query("missing_count > 0").sort_values("missing_percent", ascending=False)

                                missing_count  missing_percent
PREPARER_PHONE_NUM                    1440843       100.000000
PREPARER_NAME                         1440843       100.000000
PREPARER_FOREIGN_POSTAL_CD            1440843       100.000000
PREPARER_FOREIGN_CNTRY                1440843       100.000000
PREPARER_FOREIGN_PROV_STATE           1440843       100.000000
PREPARER_FOREIGN_CITY                 1440843       100.000000
PREPARER_FOREIGN_ADDRESS2             1440843       100.000000
PREPARER_PHONE_NUM_FOREIGN            1440843       100.000000
PREPARER_FOREIGN_ADDRESS1             1440843       100.000000
PREPARER_US_ZIP                       1440843       100.000000
PREPARER_US_STATE                     1440843       100.000000
ADMIN_ADDRESS_SAME_SPON_IND           1440843       100.000000
PREPARER_US_CITY                      1440843       100.000000
PREPARER_US_ADDRESS2                  1440843       100.000000
PREPARER_US_ADDRESS1                  1440843       100.000000
PREPARER_FIRM_NAME                    1440843       100.000000
ADMIN_FOREIGN_ADDRESS2                1440803        99.997224
SPONS_DFE_LOC_FOREIGN_ADDRESS2        1440758        99.994101
SPONS_DFE_LOC_FORGN_PROV_ST           1440727        99.991949
ADMIN_FOREIGN_PROV_STATE              1440724        99.991741
ADMIN_FOREIGN_POSTAL_CD               1440717        99.991255
ADMIN_FOREIGN_CITY                    1440707        99.990561
ADMIN_FOREIGN_ADDRESS1                1440707        99.990561
ADMIN_FOREIGN_CNTRY                   1440707        99.990561
SPONS_DFE_LOC_FORGN_POSTAL_CD         1440678        99.988548
SPONS_DFE_LOC_FOREIGN_CNTRY           1440662        99.987438
SPONS_DFE_LOC_FOREIGN_CITY            1440662        99.987438
SPONS_DFE_LOC_FOREIGN_ADDRESS1        1440662        99.987438
SPONS_DFE_MAIL_FOREIGN_ADDR2          1440449        99.972655
ADMIN_PHONE_NUM_FOREIGN               1440298        99.962175
SPONS_DFE_PHONE_NUM_FOREIGN           1439830        99.929694
SPONS_DFE_MAIL_FORGN_PROV_ST          1439675        99.918936
SPONS_DFE_MAIL_FORGN_POSTAL_CD        1439601        99.913800
SPONS_DFE_MAIL_FOREIGN_CNTRY          1439510        99.907485
SPONS_DFE_MAIL_FOREIGN_CITY           1439510        99.907485
SPONS_DFE_MAIL_FOREIGN_ADDR1          1439510        99.907485
M1_RECEIPT_CONFIRMATION_CODE          1433273        99.474613
EXT_SPECIAL_TEXT                      1431608        99.359056
DFE_MANUAL_SIGNED_DATE                1431598        99.358362
DFE_MANUAL_SIGNED_NAME                1431559        99.355655
SPONS_DFE_LOC_US_ADDRESS2             1428496        99.143071
NUM_SCH_DCG_ATTACHED_CNT              1424538        98.868371
ADMIN_CARE_OF_NAME                    1420030        98.555498
ADMIN_US_ADDRESS2                     1417775        98.398993
COMPLIANCE_M1_FILING_REQ_IND          1414279        98.156357
LAST_RPT_PLAN_NUM                     1395152        96.828870
LAST_RPT_SPONS_EIN                    1394840        96.807216
LAST_RPT_PLAN_NAME                    1393610        96.721850
LAST_RPT_SPONS_NAME                   1393401        96.707344
DFE_SIGNED_NAME                       1391981        96.608791
DFE_SIGNED_DATE                       1391981        96.608791
VALID_DFE_SIGNATURE                   1391981        96.608791
SPONS_DFE_CARE_OF_NAME                1387412        96.291685
SPONS_DFE_DBA_NAME                    1385278        96.143577
TYPE_DFE_PLAN_ENTITY_CD               1381772        95.900247
SPONS_MANUAL_SIGNED_DATE              1372432        95.252016
SPONS_MANUAL_SIGNED_NAME              1372198        95.235775
ADMIN_PHONE_NUM                       1330154        92.317761
ADMIN_US_ADDRESS1                     1328778        92.222262
ADMIN_US_STATE                        1328777        92.222192
ADMIN_US_CITY                         1328777        92.222192
ADMIN_US_ZIP                          1328777        92.222192
ADMIN_EIN                             1328736        92.219347
ADMIN_NAME                            1328633        92.212198
SPONS_DFE_LOC_US_ADDRESS1             1312000        91.057804
SPONS_DFE_LOC_US_STATE                1311999        91.057735
SPONS_DFE_LOC_US_CITY                 1311999        91.057735
SPONS_DFE_LOC_US_ZIP                  1311999        91.057735
CONTRIB_EMPLRS_CNT                    1280326        88.859508
VALID_SPONSOR_SIGNATURE               1221926        84.806325
SPONS_SIGNED_DATE                     1221921        84.805978
SPONS_SIGNED_NAME                     1221900        84.804521
PARTCP_ACCOUNT_BAL_CNT_BOY            1197893        83.138343
SPONS_DFE_MAIL_US_ADDRESS2            1192624        82.772655
SCH_DCG_ATTACHED_IND                  1164411        80.814565
SCH_MEP_ATTACHED_IND                  1115878        77.446189
ADMIN_MANUAL_SIGNED_DATE              1068583        74.163736
ADMIN_MANUAL_SIGNED_NAME              1067859        74.113488
TYPE_WELFARE_BNFT_CODE                 913748        63.417597
SUBJ_M1_FILING_REQ_IND                 906726        62.930243
ADOPTED_PLAN_PERM_SEC_ACT              828100        57.473299
NUM_SCH_A_ATTACHED_CNT                 704940        48.925525
SEP_PARTCP_PARTL_VSTD_CNT              643960        44.693280
PARTCP_ACCOUNT_BAL_CNT                 629449        43.686162
BENEF_RCVG_BNFT_CNT                    627110        43.523826
TYPE_PENSION_BNFT_CODE                 581095        40.330209
TOT_ACT_RTD_SEP_BENEF_CNT              510024        35.397611
BENEFIT_SEC412_IND                     453157        31.450824
FUNDING_SEC412_IND                     453105        31.447215
ADMIN_SIGNED_NAME                      429339        29.797764
VALID_ADMIN_SIGNATURE                  429339        29.797764
ADMIN_SIGNED_DATE                      429338        29.797695
EXT_SPECIAL_IND                        414663        28.779194
DFVC_PROGRAM_IND                       396371        27.509659
AMENDED_IND                            393678        27.322755
SCH_SB_ATTACHED_IND                    392599        27.247868
SCH_G_ATTACHED_IND                     381533        26.479845
EXT_AUTOMATIC_IND                      377720        26.215209
SCH_MB_ATTACHED_IND                    376044        26.098888
SHORT_PLAN_YR_IND                      368339        25.564132
FINAL_FILING_IND                       304862        21.158586
INITIAL_FILING_IND                     302042        20.962867
COLLECTIVE_BARGAIN_IND                 298541        20.719884
BENEFIT_GEN_ASSET_IND                  295942        20.539504
FUNDING_GEN_ASSET_IND                  294056        20.408608
SCH_I_ATTACHED_IND                     293231        20.351350
SCH_D_ATTACHED_IND                     291084        20.202340
SCH_R_ATTACHED_IND                     278807        19.350269
SCH_C_ATTACHED_IND                     277715        19.274480
SCH_H_ATTACHED_IND                     256052        17.770985
BENEFIT_INSURANCE_IND                  209953        14.571539
FUNDING_INSURANCE_IND                  207521        14.402749
BENEFIT_TRUST_IND                      207181        14.379152
FUNDING_TRUST_IND                      206922        14.361176
RTD_SEP_PARTCP_FUT_CNT                 193699        13.443449
RTD_SEP_PARTCP_RCVG_CNT                177956        12.350825
F5558_APPLICATION_FILED_IND            157283        10.916040
SCH_A_ATTACHED_IND                     134759         9.352789
ADMIN_NAME_SAME_SPON_IND               112210         7.787802
TOT_ACT_PARTCP_BOY_CNT                  67143         4.659980
TOT_ACTIVE_PARTCP_CNT                   59358         4.119672
PLAN_EFF_DATE                           55091         3.823526
TOT_PARTCP_BOY_CNT                      52590         3.649947
BUSINESS_CODE                           50406         3.498369
SUBTL_ACT_RTD_SEP_CNT                   41108         2.853052
SPONS_DFE_PHONE_NUM                      8495         0.589585
SPONS_DFE_MAIL_US_ADDRESS1               1459         0.101260
SPONS_DFE_MAIL_US_ZIP                    1458         0.101191
SPONS_DFE_MAIL_US_STATE                  1458         0.101191
SPONS_DFE_MAIL_US_CITY                   1458         0.101191
TYPE_PLAN_ENTITY_CD                       168         0.011660
PLAN_NAME                                  17         0.001180

In [11]:
# SCH_A missing data
pd.DataFrame({
    "missing_count": SCH_A.isna().sum(),
    "missing_percent": SCH_A.isna().mean().mul(100)
}).query("missing_count > 0").sort_values("missing_percent", ascending=False)

                                missing_count  missing_percent
PENSION_COST_TEXT                     2013128        99.960624
ALLOC_CONTRACTS_OTHER_TEXT            2009784        99.794580
PENSION_CONTRACT_COST_AMT             2008029        99.707436
WLFR_ACQUIS_COST_TEXT                 2007431        99.677743
PENSION_UNPAID_PREMIUM_AMT            2004967        99.555395
PENSION_BASIS_RATES_TEXT              2004404        99.527439
PENSION_PREM_PAID_TOT_AMT             1997747        99.196890
WLFR_ACQUIS_COST_AMT                  1954183        97.033747
WLFR_DIVNDS_DUE_AMT                   1953003        96.975154
WLFR_HELD_BNFTS_AMT                   1952175        96.934041
WLFR_OTH_RESERVE_AMT                  1951212        96.886223
WLFR_REFUND_AMT                       1947721        96.712880
WLFR_RESERVE_AMT                      1944661        96.560938
WLFR_RET_OTH_COST_AMT                 1943077        96.482285
WLFR_UNPAID_DUE_AMT                   1929725        95.819300
WLFR_RET_OTH_CHRGS_AMT                1927076        95.687765
INS_FAIL_PROVIDE_INFO_TEXT            1925537        95.611347
WLFR_RET_OTH_EXPENSE_AMT              1922276        95.449424
WLFR_CLAIMS_RESERVE_AMT               1915721        95.123940
PENSION_OTH_DED_TEXT                  1913957        95.036349
WLFR_RET_TAXES_AMT                    1909472        94.813650
WLFR_RET_CHARGES_AMT                  1906190        94.650684
PENSION_DIVND_CR_DEP_AMT              1906187        94.650535
WLFR_INCR_RESERVE_AMT                 1902569        94.470885
WLFR_CLAIMS_CHRGD_AMT                 1900251        94.355787
WLFR_RET_ADMIN_AMT                    1895846        94.137059
WLFR_RET_COMMISSIONS_AMT              1891730        93.932682
PENSION_OTHER_TEXT                    1879967        93.348597
UNALLOC_CONTRACTS_OTHER_TEXT          1877492        93.225702
PENSION_TRANSFER_TO_AMT               1873821        93.043421
WLFR_CLAIMS_PAID_AMT                  1873730        93.038903
PENSION_OTH_DED_AMT                   1873479        93.026439
PENSION_TRANSFER_FROM_AMT             1869123        92.810145
WLFR_PREMIUM_RCVD_AMT                 1856161        92.166525
PENSION_OTHER_AMT                     1850660        91.893376
PENSION_ADMIN_CHRG_AMT                1842787        91.502447
PENSION_CONTRIB_DEP_AMT               1829854        90.860267
PENSION_BNFTS_DSBRSD_AMT              1825054        90.621926
PENSION_INT_CR_DUR_YR_AMT             1806300        89.690708
PENSION_EOY_SEP_ACCT_AMT              1801810        89.467760
PENSION_EOY_GEN_ACCT_AMT              1798125        89.284783
WLFR_TYPE_BNFT_OTH_TEXT               1334963        66.286761
PENSION_END_PREV_BAL_AMT              1135344        56.374803
WLFR_INCURRED_CLAIM_AMT                941677        46.758388
WLFR_RET_TOT_AMT                       939366        46.643637
PENSION_TOT_BAL_ADDN_AMT               897981        44.588690
WLFR_TOT_EARNED_PREM_AMT               861460        42.775263
PENSION_TOT_DED_AMT                    840382        41.728648
PENSION_TOT_ADDITIONS_AMT              837718        41.596368
PENSION_EOY_BAL_AMT                    821774        40.804679
ALLOC_CONTRACTS_GROUP_IND              690503        34.286499
ALLOC_CONTRACTS_OTHER_IND              688449        34.184509
ALLOC_CONTRACTS_INDIV_IND              686615        34.093443
UNAL_CONTRAC_IMM_PART_GUAR_IND         686320        34.078795
UNALLOC_CONTRACTS_DEP_ADM_IND          682634        33.895769
UNAL_CONTRACTS_GUAR_INVEST_IND         672528        33.393961
WLFR_REFUND_CASH_IND                   659802        32.762060
WLFR_REFUND_CREDIT_IND                 659646        32.754314
PENS_DISTR_BNFT_TERM_PLN_IND           653608        32.454500
UNALLOC_CONTRACTS_OTHER_IND            645101        32.032091
WLFR_BNFT_STOP_LOSS_IND                604309        30.006589
WLFR_BNFT_UNEMP_IND                    584827        29.039222
WLFR_BNFT_INDEMNITY_IND                565214        28.065351
WLFR_BNFT_HMO_IND                      553377        27.477592
WLFR_BNFT_PPO_IND                      550517        27.335581
WLFR_BNFT_TEMP_DISAB_IND               520109        25.825690
WLFR_BNFT_LONG_TERM_DISAB_IND          508396        25.244089
WLFR_BNFT_DRUG_IND                     501283        24.890897
WLFR_BNFT_DENTAL_IND                   476154        23.643132
WLFR_BNFT_VISION_IND                   471046        23.389497
WLFR_BNFT_HEALTH_IND                   467363        23.206620
WLFR_BNFT_LIFE_INSUR_IND               466142        23.145992
WLFR_TOT_CHARGES_PAID_AMT              410547        20.385457
WLFR_BNFT_OTHER_IND                    407595        20.238877
INS_BROKER_FEES_TOT_AMT                360592        17.904972
INS_BROKER_COMM_TOT_AMT                292837        14.540640
INS_FAIL_PROVIDE_INFO_IND               44095         2.189510
INS_PRSN_COVERED_EOY_CNT                26927         1.337044
INS_CARRIER_NAIC_CODE                   11824         0.587113
INS_CONTRACT_NUM                        11640         0.577977
INS_POLICY_FROM_DATE                     8117         0.403045
INS_POLICY_TO_DATE                       5865         0.291223
INS_CARRIER_EIN                          5084         0.252443
INS_CARRIER_NAME                         1006         0.049952

In [12]:
# SCH_C_P1_I2 missing data
pd.DataFrame({
    "missing_count": SCH_C_P1_I2.isna().sum(),
    "missing_percent": SCH_C_P1_I2.isna().mean().mul(100)
}).query("missing_count > 0").sort_values("missing_percent", ascending=False)

                                missing_count  missing_percent
PROVIDER_OTHER_SRVC_CODES             1691315       100.000000
PROV_OTHER_FOREIGN_ADDRESS2           1689235        99.877019
PROV_OTHER_FOREIGN_PROV_STATE         1686624        99.722642
PROV_OTHER_FOREIGN_POSTAL_CD          1686424        99.710817
PROV_OTHER_FOREIGN_CNTRY              1686030        99.687521
PROV_OTHER_FOREIGN_ADDRESS1           1686021        99.686989
PROV_OTHER_FOREIGN_CITY               1686021        99.686989
PROVIDER_OTHER_US_ADDRESS2            1614549        95.461165
PROVIDER_OTHER_US_ADDRESS1            1249665        73.887182
PROVIDER_OTHER_US_CITY                1249660        73.886887
PROVIDER_OTHER_US_STATE               1249659        73.886828
PROVIDER_OTHER_US_ZIP                 1249659        73.886828
PROVIDER_OTHER_AMT_FORMULA_IND         948260        56.066434
PROV_OTHER_TOT_IND_COMP_AMT            937066        55.404582
PROV_OTHER_ELIG_IND_COMP_IND           920120        54.402639
PROVIDER_OTHER_EIN                     298219        17.632375
PROVIDER_OTHER_RELATION                 45059         2.664140
PROV_OTHER_INDIRECT_COMP_IND            15751         0.931287
PROVIDER_OTHER_DIRECT_COMP_AMT           9880         0.584161
PROVIDER_OTHER_NAME                       906         0.053568