# Innovation Summit 2026 Exploratory Data Analysis: Form 5500

This is a notebook of exploratory data analysis, made by Corey Michaud, for the Deloitte Innovation Summit 2026 Competition as a part of the Data Atlas team.

## Libraries

In [ ]:
# Libraries
import pandas as pd
import duckdb
from benefits_market_intelligence.config.paths import DB_PATH

In [ ]:
# Displaying all
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

## Load Form 5500 data

In [3]:
# Loading data
with duckdb.connect(DB_PATH, read_only=True) as con:
    F_5500 = con.sql("SELECT * FROM silver.F_5500").df()

## Viewing data

In [4]:
# Head of F5500
F_5500.head()

,ACK_ID,ADMIN_ADDRESS_SAME_SPON_IND,ADMIN_CARE_OF_NAME,ADMIN_EIN,ADMIN_FOREIGN_ADDRESS1,ADMIN_FOREIGN_ADDRESS2,ADMIN_FOREIGN_CITY,ADMIN_FOREIGN_CNTRY,ADMIN_FOREIGN_POSTAL_CD,ADMIN_FOREIGN_PROV_STATE,...,TOT_ACT_RTD_SEP_BENEF_CNT,TOT_PARTCP_BOY_CNT,TYPE_DFE_PLAN_ENTITY_CD,TYPE_PENSION_BNFT_CODE,TYPE_PLAN_ENTITY_CD,TYPE_WELFARE_BNFT_CODE,VALID_ADMIN_SIGNATURE,VALID_DFE_SIGNATURE,VALID_SPONSOR_SIGNATURE,FORM_YEAR
0,20200324164957NAL0006771024001,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,765.0,NaN,NaN,2,4A4B4D4E4F4H4L4Q,Filed with authorized/valid electronic signature,NaN,NaN,2019
1,20200324105626NAL0010195186001,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,2L,2,NaN,Filed with authorized/valid electronic signature,NaN,NaN,2019
2,20200324105715NAL0010195522001,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,34.0,NaN,2A2E2F2G2J2R2T3D,2,NaN,Filed with authorized/valid electronic signature,NaN,NaN,2019
3,20200324105729NAL0006723568001,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,2L,2,NaN,Filed with authorized/valid electronic signature,NaN,NaN,2019
4,20200324105821NAL0006724848001,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,2L,2,NaN,Filed with authorized/valid electronic signature,NaN,NaN,2019

## Shape of data

In [5]:
# Shape
print(f"Rows: {F_5500.shape[0]}\nColumns: {F_5500.shape[1]}")

Rows: 1440843
Columns: 141

## Data types

In [6]:
# Data type counts
F_5500.dtypes.value_counts()

str               102
object             16
float64            13
datetime64[us]      9
int32               1
Name: count, dtype: int64

## Any missing data?

In [7]:
# Columns with no missing data
F_5500.isna().sum()[F_5500.isna().sum() == 0]

ACK_ID                       0
DATE_RECEIVED                0
FILING_STATUS                0
FORM_PLAN_YEAR_BEGIN_DATE    0
FORM_TAX_PRD                 0
PLAN_NAME                    0
SPONSOR_DFE_NAME             0
SPONS_DFE_EIN                0
SPONS_DFE_PN                 0
FORM_YEAR                    0
dtype: int64

In [8]:
# Missing data
pd.DataFrame(
    {
        "missing_count": F_5500.isna().sum(),
        "missing_percent": F_5500.isna().mean().mul(100),
    }
).query("missing_count > 0").sort_values(
    "missing_percent", ascending=False
).rename_axis("column_name").reset_index()

                        column_name  missing_count  missing_percent
0       ADMIN_ADDRESS_SAME_SPON_IND        1440843       100.000000
1                PREPARER_FIRM_NAME        1440843       100.000000
2                   PREPARER_US_ZIP        1440843       100.000000
3                 PREPARER_US_STATE        1440843       100.000000
4                  PREPARER_US_CITY        1440843       100.000000
5              PREPARER_US_ADDRESS2        1440843       100.000000
6              PREPARER_US_ADDRESS1        1440843       100.000000
7        PREPARER_PHONE_NUM_FOREIGN        1440843       100.000000
8                PREPARER_PHONE_NUM        1440843       100.000000
9       PREPARER_FOREIGN_PROV_STATE        1440843       100.000000
10       PREPARER_FOREIGN_POSTAL_CD        1440843       100.000000
11           PREPARER_FOREIGN_CNTRY        1440843       100.000000
12            PREPARER_FOREIGN_CITY        1440843       100.000000
13        PREPARER_FOREIGN_ADDRESS2        1440843       100.000000
14        PREPARER_FOREIGN_ADDRESS1        1440843       100.000000
15                    PREPARER_NAME        1440843       100.000000
16           ADMIN_FOREIGN_ADDRESS2        1440803        99.997224
17   SPONS_DFE_LOC_FOREIGN_ADDRESS2        1440758        99.994101
18      SPONS_DFE_LOC_FORGN_PROV_ST        1440727        99.991949
19         ADMIN_FOREIGN_PROV_STATE        1440724        99.991741
20          ADMIN_FOREIGN_POSTAL_CD        1440717        99.991255
21              ADMIN_FOREIGN_CNTRY        1440707        99.990561
22               ADMIN_FOREIGN_CITY        1440707        99.990561
23           ADMIN_FOREIGN_ADDRESS1        1440707        99.990561
24    SPONS_DFE_LOC_FORGN_POSTAL_CD        1440678        99.988548
25   SPONS_DFE_LOC_FOREIGN_ADDRESS1        1440662        99.987438
26      SPONS_DFE_LOC_FOREIGN_CNTRY        1440662        99.987438
27       SPONS_DFE_LOC_FOREIGN_CITY        1440662        99.987438
28     SPONS_DFE_MAIL_FOREIGN_ADDR2        1440449        99.972655
29          ADMIN_PHONE_NUM_FOREIGN        1440298        99.962175
30      SPONS_DFE_PHONE_NUM_FOREIGN        1439830        99.929694
31     SPONS_DFE_MAIL_FORGN_PROV_ST        1439675        99.918936
32   SPONS_DFE_MAIL_FORGN_POSTAL_CD        1439601        99.913800
33     SPONS_DFE_MAIL_FOREIGN_ADDR1        1439510        99.907485
34     SPONS_DFE_MAIL_FOREIGN_CNTRY        1439510        99.907485
35      SPONS_DFE_MAIL_FOREIGN_CITY        1439510        99.907485
36     M1_RECEIPT_CONFIRMATION_CODE        1433273        99.474613
37                 EXT_SPECIAL_TEXT        1431608        99.359056
38           DFE_MANUAL_SIGNED_DATE        1431598        99.358362
39           DFE_MANUAL_SIGNED_NAME        1431558        99.355586
40        SPONS_DFE_LOC_US_ADDRESS2        1428495        99.143002
41         NUM_SCH_DCG_ATTACHED_CNT        1424538        98.868371
42               ADMIN_CARE_OF_NAME        1420027        98.555290
43                ADMIN_US_ADDRESS2        1417775        98.398993
44     COMPLIANCE_M1_FILING_REQ_IND        1414279        98.156357
45                LAST_RPT_PLAN_NUM        1395152        96.828870
46               LAST_RPT_SPONS_EIN        1394840        96.807216
47               LAST_RPT_PLAN_NAME        1393602        96.721294
48              LAST_RPT_SPONS_NAME        1393385        96.706234
49                  DFE_SIGNED_NAME        1391981        96.608791
50                  DFE_SIGNED_DATE        1391981        96.608791
51              VALID_DFE_SIGNATURE        1391981        96.608791
52           SPONS_DFE_CARE_OF_NAME        1387405        96.291199
53               SPONS_DFE_DBA_NAME        1385262        96.142467
54          TYPE_DFE_PLAN_ENTITY_CD        1381772        95.900247
55         SPONS_MANUAL_SIGNED_DATE        1372432        95.252016
56         SPONS_MANUAL_SIGNED_NAME        1372198        95.235775
57                  ADMIN_PHONE_NUM        1330154        92.317761
58                ADMIN_US_ADDRESS1        1328777        92.222192
59                     ADMIN_US_ZIP        1328777        92.222192
60                   ADMIN_US_STATE        1328777        92.222192
61                    ADMIN_US_CITY        1328777        92.222192
62                        ADMIN_EIN        1328736        92.219347
63                       ADMIN_NAME        1328633        92.212198
64             SPONS_DFE_LOC_US_ZIP        1311999        91.057735
65           SPONS_DFE_LOC_US_STATE        1311999        91.057735
66            SPONS_DFE_LOC_US_CITY        1311999        91.057735
67        SPONS_DFE_LOC_US_ADDRESS1        1311999        91.057735
68               CONTRIB_EMPLRS_CNT        1280326        88.859508
69          VALID_SPONSOR_SIGNATURE        1221926        84.806325
70                SPONS_SIGNED_DATE        1221921        84.805978
71                SPONS_SIGNED_NAME        1221900        84.804521
72       PARTCP_ACCOUNT_BAL_CNT_BOY        1197893        83.138343
73       SPONS_DFE_MAIL_US_ADDRESS2        1192622        82.772516
74             SCH_DCG_ATTACHED_IND        1164411        80.814565
75             SCH_MEP_ATTACHED_IND        1115878        77.446189
76         ADMIN_MANUAL_SIGNED_DATE        1068583        74.163736
77         ADMIN_MANUAL_SIGNED_NAME        1067859        74.113488
78           TYPE_WELFARE_BNFT_CODE         913748        63.417597
79           SUBJ_M1_FILING_REQ_IND         906726        62.930243
80        ADOPTED_PLAN_PERM_SEC_ACT         828100        57.473299
81           NUM_SCH_A_ATTACHED_CNT         704940        48.925525
82        SEP_PARTCP_PARTL_VSTD_CNT         643960        44.693280
83           PARTCP_ACCOUNT_BAL_CNT         629449        43.686162
84              BENEF_RCVG_BNFT_CNT         627110        43.523826
85           TYPE_PENSION_BNFT_CODE         581095        40.330209
86        TOT_ACT_RTD_SEP_BENEF_CNT         510024        35.397611
87               BENEFIT_SEC412_IND         453157        31.450824
88               FUNDING_SEC412_IND         453105        31.447215
89            VALID_ADMIN_SIGNATURE         429339        29.797764
90                ADMIN_SIGNED_NAME         429339        29.797764
91                ADMIN_SIGNED_DATE         429338        29.797695
92                  EXT_SPECIAL_IND         414663        28.779194
93                 DFVC_PROGRAM_IND         396371        27.509659
94                      AMENDED_IND         393678        27.322755
95              SCH_SB_ATTACHED_IND         392599        27.247868
96               SCH_G_ATTACHED_IND         381533        26.479845
97                EXT_AUTOMATIC_IND         377720        26.215209
98              SCH_MB_ATTACHED_IND         376044        26.098888
99                SHORT_PLAN_YR_IND         368339        25.564132
100                FINAL_FILING_IND         304862        21.158586
101              INITIAL_FILING_IND         302042        20.962867
102          COLLECTIVE_BARGAIN_IND         298541        20.719884
103           BENEFIT_GEN_ASSET_IND         295942        20.539504
104           FUNDING_GEN_ASSET_IND         294056        20.408608
105              SCH_I_ATTACHED_IND         293231        20.351350
106              SCH_D_ATTACHED_IND         291084        20.202340
107              SCH_R_ATTACHED_IND         278807        19.350269
108              SCH_C_ATTACHED_IND         277715        19.274480
109              SCH_H_ATTACHED_IND         256052        17.770985
110           BENEFIT_INSURANCE_IND         209953        14.571539
111           FUNDING_INSURANCE_IND         207521        14.402749
112               BENEFIT_TRUST_IND         207181        14.379152
113               FUNDING_TRUST_IND         206922        14.361176
114          RTD_SEP_PARTCP_FUT_CNT         193699        13.443449
115         RTD_SEP_PARTCP_RCVG_CNT         177956        12.350825
116     F5558_APPLICATION_FILED_IND         157283        10.916040
117              SCH_A_ATTACHED_IND         134759         9.352789
118        ADMIN_NAME_SAME_SPON_IND         112210         7.787802
119          TOT_ACT_PARTCP_BOY_CNT          67143         4.659980
120           TOT_ACTIVE_PARTCP_CNT          59358         4.119672
121                   PLAN_EFF_DATE          55091         3.823526
122              TOT_PARTCP_BOY_CNT          52590         3.649947
123                   BUSINESS_CODE          50406         3.498369
124           SUBTL_ACT_RTD_SEP_CNT          41108         2.853052
125             SPONS_DFE_PHONE_NUM           8495         0.589585
126         SPONS_DFE_MAIL_US_STATE           1458         0.101191
127          SPONS_DFE_MAIL_US_CITY           1458         0.101191
128      SPONS_DFE_MAIL_US_ADDRESS1           1458         0.101191
129           SPONS_DFE_MAIL_US_ZIP           1458         0.101191
130             TYPE_PLAN_ENTITY_CD            168         0.011660