# Benefits Market Intelligence Exploratory Data Analysis: Form 5500

## Libraries

In [20]:
# Libraries
import pandas as pd
import duckdb
from benefits_market_intelligence.config.paths import DB_PATH

In [21]:
# Displaying all
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

## Load Form 5500 data

In [22]:
# Loading data
with duckdb.connect(DB_PATH, read_only=True) as con:
    F_5500 = con.sql("SELECT * FROM silver.F_5500").df()

In [23]:
# Convert pandas-made object columns to string
obj_cols = F_5500.dtypes[F_5500.dtypes == "object"].index
F_5500[obj_cols] = F_5500[obj_cols].astype("str")

## Viewing data

In [24]:
# Head of F5500
F_5500.head()

,ACK_ID,ADMIN_ADDRESS_SAME_SPON_IND,ADMIN_CARE_OF_NAME,ADMIN_EIN,ADMIN_FOREIGN_ADDRESS1,ADMIN_FOREIGN_ADDRESS2,ADMIN_FOREIGN_CITY,ADMIN_FOREIGN_CNTRY,ADMIN_FOREIGN_POSTAL_CD,ADMIN_FOREIGN_PROV_STATE,ADMIN_MANUAL_SIGNED_DATE,ADMIN_MANUAL_SIGNED_NAME,ADMIN_NAME,ADMIN_NAME_SAME_SPON_IND,ADMIN_PHONE_NUM,ADMIN_PHONE_NUM_FOREIGN,ADMIN_SIGNED_DATE,ADMIN_SIGNED_NAME,ADMIN_US_ADDRESS1,ADMIN_US_ADDRESS2,ADMIN_US_CITY,ADMIN_US_STATE,ADMIN_US_ZIP,ADOPTED_PLAN_PERM_SEC_ACT,AMENDED_IND,BENEFIT_GEN_ASSET_IND,BENEFIT_INSURANCE_IND,BENEFIT_SEC412_IND,BENEFIT_TRUST_IND,BENEF_RCVG_BNFT_CNT,BUSINESS_CODE,COLLECTIVE_BARGAIN_IND,COMPLIANCE_M1_FILING_REQ_IND,CONTRIB_EMPLRS_CNT,DATE_RECEIVED,DFE_MANUAL_SIGNED_DATE,DFE_MANUAL_SIGNED_NAME,DFE_SIGNED_DATE,DFE_SIGNED_NAME,DFVC_PROGRAM_IND,EXT_AUTOMATIC_IND,EXT_SPECIAL_IND,EXT_SPECIAL_TEXT,F5558_APPLICATION_FILED_IND,FILING_STATUS,FINAL_FILING_IND,FORM_PLAN_YEAR_BEGIN_DATE,FORM_TAX_PRD,FUNDING_GEN_ASSET_IND,FUNDING_INSURANCE_IND,FUNDING_SEC412_IND,FUNDING_TRUST_IND,INITIAL_FILING_IND,LAST_RPT_PLAN_NAME,LAST_RPT_PLAN_NUM,LAST_RPT_SPONS_EIN,LAST_RPT_SPONS_NAME,M1_RECEIPT_CONFIRMATION_CODE,NUM_SCH_A_ATTACHED_CNT,NUM_SCH_DCG_ATTACHED_CNT,PARTCP_ACCOUNT_BAL_CNT,PARTCP_ACCOUNT_BAL_CNT_BOY,PLAN_EFF_DATE,PLAN_NAME,PREPARER_FIRM_NAME,PREPARER_FOREIGN_ADDRESS1,PREPARER_FOREIGN_ADDRESS2,PREPARER_FOREIGN_CITY,PREPARER_FOREIGN_CNTRY,PREPARER_FOREIGN_POSTAL_CD,PREPARER_FOREIGN_PROV_STATE,PREPARER_NAME,PREPARER_PHONE_NUM,PREPARER_PHONE_NUM_FOREIGN,PREPARER_US_ADDRESS1,PREPARER_US_ADDRESS2,PREPARER_US_CITY,PREPARER_US_STATE,PREPARER_US_ZIP,RTD_SEP_PARTCP_FUT_CNT,RTD_SEP_PARTCP_RCVG_CNT,SCH_A_ATTACHED_IND,SCH_C_ATTACHED_IND,SCH_DCG_ATTACHED_IND,SCH_D_ATTACHED_IND,SCH_G_ATTACHED_IND,SCH_H_ATTACHED_IND,SCH_I_ATTACHED_IND,SCH_MB_ATTACHED_IND,SCH_MEP_ATTACHED_IND,SCH_R_ATTACHED_IND,SCH_SB_ATTACHED_IND,SEP_PARTCP_PARTL_VSTD_CNT,SHORT_PLAN_YR_IND,SPONSOR_DFE_NAME,SPONS_DFE_CARE_OF_NAME,SPONS_DFE_DBA_NAME,SPONS_DFE_EIN,SPONS_DFE_LOC_FOREIGN_ADDRESS1,SPONS_DFE_LOC_FOREIGN_ADDRESS2,SPONS_DFE_LOC_FOREIGN_CITY,SPONS_DFE_LOC_FOREIGN_CNTRY,SPONS_DFE_LOC_FORGN_POSTAL_CD,SPONS_DFE_LOC_FORGN_PROV_ST,SPONS_DFE_LOC_US_ADDRESS1,SPONS_DFE_LOC_US_ADDRESS2,SPONS_DFE_LOC_US_CITY,SPONS_DFE_LOC_US_STATE,SPONS_DFE_LOC_US_ZIP,SPONS_DFE_MAIL_FOREIGN_ADDR1,SPONS_DFE_MAIL_FOREIGN_ADDR2,SPONS_DFE_MAIL_FOREIGN_CITY,SPONS_DFE_MAIL_FOREIGN_CNTRY,SPONS_DFE_MAIL_FORGN_POSTAL_CD,SPONS_DFE_MAIL_FORGN_PROV_ST,SPONS_DFE_MAIL_US_ADDRESS1,SPONS_DFE_MAIL_US_ADDRESS2,SPONS_DFE_MAIL_US_CITY,SPONS_DFE_MAIL_US_STATE,SPONS_DFE_MAIL_US_ZIP,SPONS_DFE_PHONE_NUM,SPONS_DFE_PHONE_NUM_FOREIGN,SPONS_DFE_PN,SPONS_MANUAL_SIGNED_DATE,SPONS_MANUAL_SIGNED_NAME,SPONS_SIGNED_DATE,SPONS_SIGNED_NAME,SUBJ_M1_FILING_REQ_IND,SUBTL_ACT_RTD_SEP_CNT,TOT_ACTIVE_PARTCP_CNT,TOT_ACT_PARTCP_BOY_CNT,TOT_ACT_RTD_SEP_BENEF_CNT,TOT_PARTCP_BOY_CNT,TYPE_DFE_PLAN_ENTITY_CD,TYPE_PENSION_BNFT_CODE,TYPE_PLAN_ENTITY_CD,TYPE_WELFARE_BNFT_CODE,VALID_ADMIN_SIGNATURE,VALID_DFE_SIGNATURE,VALID_SPONSOR_SIGNATURE,FORM_YEAR
0,20200324164957NAL0006771024001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,1,NaN,NaN,2020-03-24,KRISTY EZELL,NaN,NaN,NaN,NaN,NaN,NaN,0,1,1,0,0,NaN,722513,0,NaN,NaN,2020-03-24,NaT,NaN,NaT,NaN,0,0,0,NaN,0,FILING_RECEIVED,0,2019-01-01,2019-12-31,1,1,0,0,0,NaN,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN,1997-01-01,TACALA LLC HEALTH AND WELFARE BENEFIT PROGRAM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,3.0,1,0,NaN,0,0,0,0,0,NaN,0,0,NaN,0,TACALA LLC,NaN,NaN,631205373,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3750 CORPORATE WOODS DRIVE,NaN,VESTAVIA HILLS,AL,35242,2054439642,NaN,501,NaT,NaN,NaT,NaN,2,701.0,698.0,763.0,NaN,765.0,NaN,NaN,2,4A4B4D4E4F4H4L4Q,Filed with authorized/valid electronic signature,NaN,NaN,2019
1,20200324105626NAL0010195186001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,1,NaN,NaN,2020-03-24,MICHAEL FREDERICK,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,NaN,611000,0,NaN,NaN,2020-03-24,NaT,NaN,NaT,NaN,1,0,0,NaN,0,FILING_RECEIVED,0,1998-01-01,1998-12-31,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,1996-01-01,THE THOREAU SOCIETY DEFERRED ANNUITY PLAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,0,0,0,0,0,NaN,0,0,NaN,0,"THE THOREAU SOCIETY, INC.",NaN,NaN,166035496,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,341 VIRGINIA RD,NaN,CONCORD,MA,017422727,9783695310,NaN,002,NaT,NaN,NaT,NaN,NaN,0.0,NaN,NaN,0.0,0.0,NaN,2L,2,NaN,Filed with authorized/valid electronic signature,NaN,NaN,2019
2,20200324105715NAL0010195522001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,1,NaN,NaN,2020-03-24,CINDY MULLINS,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1,0,1,0.0,621111,0,NaN,NaN,2020-03-24,NaT,NaN,NaT,NaN,0,0,0,NaN,1,FILING_RECEIVED,1,2019-01-01,2019-12-12,0,1,0,1,0,NaN,NaN,NaN,NaN,NaN,1,NaN,0.0,NaN,1979-07-01,"VIRGINIA RADIOLOGY ASSOCIATES, P.C. 401K PROFI...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1,0,NaN,0,0,0,1,0,NaN,1,NaN,0.0,1,"VIRGINIA RADIOLOGY ASSOCIATES, P.C.",NaN,NaN,541080266,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PO BOX 3598,NaN,WARRENTON,VA,20188,7035093847,NaN,002,NaT,NaN,NaT,NaN,NaN,0.0,0.0,9.0,0.0,34.0,NaN,2A2E2F2G2J2R2T3D,2,NaN,Filed with authorized/valid electronic signature,NaN,NaN,2019
3,20200324105729NAL0006723568001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,1,NaN,NaN,2020-03-24,MICHAEL FREDERICK,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,NaN,611000,0,NaN,NaN,2020-03-24,NaT,NaN,NaT,NaN,1,0,0,NaN,0,FILING_RECEIVED,0,1997-01-01,1997-12-31,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,1996-01-01,THE THOREAU SOCIETY DEFERRED ANNUITY PLAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,0,0,0,0,0,NaN,0,0,NaN,0,"THE THOREAU SOCIETY, INC.",NaN,NaN,166035496,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,341 VIRGINIA RD,NaN,CONCORD,MA,017422727,9783695310,NaN,002,NaT,NaN,NaT,NaN,NaN,0.0,NaN,NaN,0.0,0.0,NaN,2L,2,NaN,Filed with authorized/valid electronic signature,NaN,NaN,2019
4,20200324105821NAL0006724848001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,1,NaN,NaN,2020-03-24,MICHAEL FREDERICK,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,NaN,611000,0,NaN,NaN,2020-03-24,NaT,NaN,NaT,NaN,1,0,0,NaN,0,FILING_RECEIVED,0,1996-01-01,1996-12-31,0,0,0,0,1,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,1996-01-01,THE THOREAU SOCIETY DEFERRED ANNUITY PLAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,0,0,0,0,0,NaN,0,0,NaN,0,"THE THOREAU SOCIETY, INC.",NaN,NaN,166035496,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,341 VIRGINIA RD,NaN,CONCORD,MA,017422727,9783695310,NaN,002,NaT,NaN,NaT,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,2L,2,NaN,Filed with authorized/valid electronic signature,NaN,NaN,2019

## Shape of data

In [25]:
# Shape
print(f"Rows: {F_5500.shape[0]}\nColumns: {F_5500.shape[1]}")

Rows: 1442027
Columns: 141

## Data types

In [26]:
# Data type counts
F_5500.dtypes.value_counts()

str               118
float64            13
datetime64[us]      9
int32               1
Name: count, dtype: int64

## Any missing data?

In [27]:
# Columns with no missing data
F_5500.isna().sum()[F_5500.isna().sum() == 0]

ACK_ID                       0
DATE_RECEIVED                0
FILING_STATUS                0
FORM_PLAN_YEAR_BEGIN_DATE    0
FORM_TAX_PRD                 0
PLAN_NAME                    0
SPONSOR_DFE_NAME             0
SPONS_DFE_EIN                0
SPONS_DFE_PN                 0
FORM_YEAR                    0
dtype: int64

In [28]:
# Missing data
pd.DataFrame(
    {
        "missing_count": F_5500.isna().sum(),
        "missing_percent": F_5500.isna().mean().mul(100),
    }
).query("missing_count > 0").sort_values(
    "missing_percent", ascending=False
).rename_axis("column_name").reset_index()

                        column_name  missing_count  missing_percent
0       ADMIN_ADDRESS_SAME_SPON_IND        1442027       100.000000
1                PREPARER_FIRM_NAME        1442027       100.000000
2                   PREPARER_US_ZIP        1442027       100.000000
3                 PREPARER_US_STATE        1442027       100.000000
4                  PREPARER_US_CITY        1442027       100.000000
5              PREPARER_US_ADDRESS2        1442027       100.000000
6              PREPARER_US_ADDRESS1        1442027       100.000000
7        PREPARER_PHONE_NUM_FOREIGN        1442027       100.000000
8                PREPARER_PHONE_NUM        1442027       100.000000
9       PREPARER_FOREIGN_PROV_STATE        1442027       100.000000
10       PREPARER_FOREIGN_POSTAL_CD        1442027       100.000000
11           PREPARER_FOREIGN_CNTRY        1442027       100.000000
12            PREPARER_FOREIGN_CITY        1442027       100.000000
13        PREPARER_FOREIGN_ADDRESS2        1442027       100.000000
14        PREPARER_FOREIGN_ADDRESS1        1442027       100.000000
15                    PREPARER_NAME        1442027       100.000000
16           ADMIN_FOREIGN_ADDRESS2        1441987        99.997226
17   SPONS_DFE_LOC_FOREIGN_ADDRESS2        1441942        99.994106
18      SPONS_DFE_LOC_FORGN_PROV_ST        1441911        99.991956
19         ADMIN_FOREIGN_PROV_STATE        1441908        99.991748
20          ADMIN_FOREIGN_POSTAL_CD        1441901        99.991262
21              ADMIN_FOREIGN_CNTRY        1441891        99.990569
22               ADMIN_FOREIGN_CITY        1441891        99.990569
23           ADMIN_FOREIGN_ADDRESS1        1441891        99.990569
24    SPONS_DFE_LOC_FORGN_POSTAL_CD        1441862        99.988558
25   SPONS_DFE_LOC_FOREIGN_ADDRESS1        1441846        99.987448
26      SPONS_DFE_LOC_FOREIGN_CNTRY        1441846        99.987448
27       SPONS_DFE_LOC_FOREIGN_CITY        1441846        99.987448
28     SPONS_DFE_MAIL_FOREIGN_ADDR2        1441633        99.972677
29          ADMIN_PHONE_NUM_FOREIGN        1441482        99.962206
30      SPONS_DFE_PHONE_NUM_FOREIGN        1441016        99.929890
31     SPONS_DFE_MAIL_FORGN_PROV_ST        1440854        99.918656
32   SPONS_DFE_MAIL_FORGN_POSTAL_CD        1440780        99.913525
33     SPONS_DFE_MAIL_FOREIGN_ADDR1        1440689        99.907214
34     SPONS_DFE_MAIL_FOREIGN_CNTRY        1440689        99.907214
35      SPONS_DFE_MAIL_FOREIGN_CITY        1440689        99.907214
36     M1_RECEIPT_CONFIRMATION_CODE        1434450        99.474559
37                 EXT_SPECIAL_TEXT        1432790        99.359443
38           DFE_MANUAL_SIGNED_DATE        1432771        99.358126
39           DFE_MANUAL_SIGNED_NAME        1432732        99.355421
40        SPONS_DFE_LOC_US_ADDRESS2        1429666        99.142804
41         NUM_SCH_DCG_ATTACHED_CNT        1425663        98.865208
42               ADMIN_CARE_OF_NAME        1421202        98.555852
43                ADMIN_US_ADDRESS2        1418955        98.400030
44     COMPLIANCE_M1_FILING_REQ_IND        1415449        98.156900
45                LAST_RPT_PLAN_NUM        1396263        96.826412
46               LAST_RPT_SPONS_EIN        1395953        96.804914
47               LAST_RPT_PLAN_NAME        1394709        96.718647
48              LAST_RPT_SPONS_NAME        1394499        96.704084
49                  DFE_SIGNED_NAME        1393156        96.610951
50                  DFE_SIGNED_DATE        1393156        96.610951
51              VALID_DFE_SIGNATURE        1393156        96.610951
52           SPONS_DFE_CARE_OF_NAME        1388542        96.290985
53               SPONS_DFE_DBA_NAME        1386380        96.141057
54          TYPE_DFE_PLAN_ENTITY_CD        1382938        95.902365
55         SPONS_MANUAL_SIGNED_DATE        1373523        95.249465
56         SPONS_MANUAL_SIGNED_NAME        1373289        95.233238
57                  ADMIN_PHONE_NUM        1331280        92.320047
58                ADMIN_US_ADDRESS1        1329902        92.224487
59                     ADMIN_US_ZIP        1329902        92.224487
60                   ADMIN_US_STATE        1329902        92.224487
61                    ADMIN_US_CITY        1329902        92.224487
62                        ADMIN_EIN        1329861        92.221644
63                       ADMIN_NAME        1329758        92.214501
64             SPONS_DFE_LOC_US_ZIP        1313000        91.052387
65           SPONS_DFE_LOC_US_STATE        1313000        91.052387
66            SPONS_DFE_LOC_US_CITY        1313000        91.052387
67        SPONS_DFE_LOC_US_ADDRESS1        1313000        91.052387
68               CONTRIB_EMPLRS_CNT        1281269        88.851942
69          VALID_SPONSOR_SIGNATURE        1222957        84.808190
70                SPONS_SIGNED_DATE        1222952        84.807843
71                SPONS_SIGNED_NAME        1222931        84.806387
72       PARTCP_ACCOUNT_BAL_CNT_BOY        1198539        83.114879
73       SPONS_DFE_MAIL_US_ADDRESS2        1193611        82.773138
74             SCH_DCG_ATTACHED_IND        1164770        80.773106
75             SCH_MEP_ATTACHED_IND        1116187        77.404029
76         ADMIN_MANUAL_SIGNED_DATE        1069335        74.154992
77         ADMIN_MANUAL_SIGNED_NAME        1068610        74.104715
78           TYPE_WELFARE_BNFT_CODE         914330        63.405886
79           SUBJ_M1_FILING_REQ_IND         907321        62.919834
80        ADOPTED_PLAN_PERM_SEC_ACT         828544        57.456899
81           NUM_SCH_A_ATTACHED_CNT         706215        48.973771
82        SEP_PARTCP_PARTL_VSTD_CNT         644651        44.704503
83           PARTCP_ACCOUNT_BAL_CNT         630151        43.698974
84              BENEF_RCVG_BNFT_CNT         627763        43.533374
85           TYPE_PENSION_BNFT_CODE         581708        40.339605
86        TOT_ACT_RTD_SEP_BENEF_CNT         510538        35.404191
87               BENEFIT_SEC412_IND         453615        31.456762
88               FUNDING_SEC412_IND         453563        31.453156
89            VALID_ADMIN_SIGNATURE         429796        29.804990
90                ADMIN_SIGNED_NAME         429796        29.804990
91                ADMIN_SIGNED_DATE         429795        29.804920
92                  EXT_SPECIAL_IND         415105        28.786216
93                 DFVC_PROGRAM_IND         396706        27.510303
94                      AMENDED_IND         393947        27.318975
95              SCH_SB_ATTACHED_IND         392992        27.252749
96               SCH_G_ATTACHED_IND         381930        26.485634
97                EXT_AUTOMATIC_IND         378158        26.224058
98              SCH_MB_ATTACHED_IND         376427        26.104019
99                SHORT_PLAN_YR_IND         368716        25.569285
100                FINAL_FILING_IND         305205        21.164999
101              INITIAL_FILING_IND         302375        20.968747
102          COLLECTIVE_BARGAIN_IND         298843        20.723814
103           BENEFIT_GEN_ASSET_IND         296280        20.546079
104           FUNDING_GEN_ASSET_IND         294391        20.415082
105              SCH_I_ATTACHED_IND         293570        20.358149
106              SCH_D_ATTACHED_IND         291423        20.209261
107              SCH_R_ATTACHED_IND         279122        19.356226
108              SCH_C_ATTACHED_IND         278000        19.278419
109              SCH_H_ATTACHED_IND         256335        17.776019
110           BENEFIT_INSURANCE_IND         210124        14.571433
111           FUNDING_INSURANCE_IND         207703        14.403544
112               BENEFIT_TRUST_IND         207398        14.382394
113               FUNDING_TRUST_IND         207138        14.364363
114          RTD_SEP_PARTCP_FUT_CNT         193889        13.445587
115         RTD_SEP_PARTCP_RCVG_CNT         178124        12.352335
116     F5558_APPLICATION_FILED_IND         157419        10.916508
117              SCH_A_ATTACHED_IND         134888         9.354055
118        ADMIN_NAME_SAME_SPON_IND         112269         7.785499
119          TOT_ACT_PARTCP_BOY_CNT          67169         4.657957
120           TOT_ACTIVE_PARTCP_CNT          59386         4.118231
121                   PLAN_EFF_DATE          55098         3.820872
122              TOT_PARTCP_BOY_CNT          52607         3.648129
123                   BUSINESS_CODE          50416         3.496190
124           SUBTL_ACT_RTD_SEP_CNT          41118         2.851403
125             SPONS_DFE_PHONE_NUM           8508         0.590003
126         SPONS_DFE_MAIL_US_STATE           1463         0.101454
127          SPONS_DFE_MAIL_US_CITY           1463         0.101454
128      SPONS_DFE_MAIL_US_ADDRESS1           1463         0.101454
129           SPONS_DFE_MAIL_US_ZIP           1463         0.101454
130             TYPE_PLAN_ENTITY_CD            168         0.011650