# Innovation Summit 2026 Exploratory Data Analysis: Form 5500 - Schedule A

This is a notebook of exploratory data analysis, made by Corey Michaud, for the Deloitte Innovation Summit 2026 Competition as a part of the Data Atlas team.

## Libraries

In [ ]:
# Libraries
import pandas as pd
import duckdb
from innovation_summit.config.paths import DB_PATH

In [2]:
# Displaying all
pd.set_option("display.max_rows", None)

## Load Form 5500 - Schedule A data

In [ ]:
# Loading data
with duckdb.connect(DB_PATH, read_only=True) as con:
    SCH_A = con.sql("SELECT * FROM silver.SCH_A").df()

## Viewing data

In [4]:
# Head of SCH_A
SCH_A.head()

,ACK_ID,ALLOC_CONTRACTS_GROUP_IND,ALLOC_CONTRACTS_INDIV_IND,ALLOC_CONTRACTS_OTHER_IND,ALLOC_CONTRACTS_OTHER_TEXT,FORM_ID,INS_BROKER_COMM_TOT_AMT,INS_BROKER_FEES_TOT_AMT,INS_CARRIER_EIN,INS_CARRIER_NAIC_CODE,...,WLFR_RET_OTH_CHRGS_AMT,WLFR_RET_OTH_COST_AMT,WLFR_RET_OTH_EXPENSE_AMT,WLFR_RET_TAXES_AMT,WLFR_RET_TOT_AMT,WLFR_TOT_CHARGES_PAID_AMT,WLFR_TOT_EARNED_PREM_AMT,WLFR_TYPE_BNFT_OTH_TEXT,WLFR_UNPAID_DUE_AMT,FORM_YEAR
0,20200407140313NAL0005903843001,NaN,NaN,NaN,NaN,1.0,NaN,NaN,470098400,61301,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019
1,20200408103626NAL0010330753001,0,0,0,NaN,1.0,4751.0,429.0,710505232,94358,...,NaN,NaN,NaN,NaN,0.0,21442.0,0.0,"AD&D, SUPPLEMENTAL/DEPENDENT LIFE",NaN,2019
2,20200408103626NAL0010330753001,0,0,0,NaN,2.0,2457.0,222.0,710505232,94358,...,NaN,NaN,NaN,NaN,0.0,11101.0,0.0,NaN,NaN,2019
3,20200408103709NAL0014724896001,0,0,0,NaN,1.0,3914.0,429.0,710505232,94358,...,NaN,NaN,NaN,NaN,0.0,21448.0,0.0,"AD&D, SUPPLEMENTAL/DEPENDENT LIFE",NaN,2019
4,20200408103709NAL0014724896001,0,0,0,NaN,2.0,2144.0,237.0,710505232,94358,...,NaN,NaN,NaN,NaN,0.0,11845.0,0.0,NaN,NaN,2019

## Shape of data

In [5]:
# Shape
print(f"Rows: {SCH_A.shape[0]}\nColumns: {SCH_A.shape[1]}")

Rows: 2013921
Columns: 91

## Data types

In [6]:
# Data type counts
SCH_A.dtypes.value_counts()

float64           45
str               41
datetime64[us]     4
int32              1
Name: count, dtype: int64

## Any missing data?

In [7]:
# Columns with no missing data
SCH_A.isna().sum()[SCH_A.isna().sum() == 0]

ACK_ID                        0
FORM_ID                       0
SCH_A_EIN                     0
SCH_A_PLAN_NUM                0
SCH_A_PLAN_YEAR_BEGIN_DATE    0
SCH_A_PLAN_YEAR_END_DATE      0
FORM_YEAR                     0
dtype: int64

In [8]:
# Missing data
pd.DataFrame(
    {
        "missing_count": SCH_A.isna().sum(),
        "missing_percent": SCH_A.isna().mean().mul(100),
    }
).query("missing_count > 0").sort_values(
    "missing_percent", ascending=False
).rename_axis("column_name").reset_index()

                       column_name  missing_count  missing_percent
0                PENSION_COST_TEXT        2012811        99.944884
1       ALLOC_CONTRACTS_OTHER_TEXT        2009783        99.794530
2        PENSION_CONTRACT_COST_AMT        2008029        99.707436
3       PENSION_UNPAID_PREMIUM_AMT        2004967        99.555395
4        PENSION_PREM_PAID_TOT_AMT        1997747        99.196890
5         PENSION_BASIS_RATES_TEXT        1995964        99.108356
6            WLFR_ACQUIS_COST_TEXT        1968866        97.762822
7             WLFR_ACQUIS_COST_AMT        1954183        97.033747
8              WLFR_DIVNDS_DUE_AMT        1953003        96.975154
9              WLFR_HELD_BNFTS_AMT        1952175        96.934041
10            WLFR_OTH_RESERVE_AMT        1951212        96.886223
11                 WLFR_REFUND_AMT        1947721        96.712880
12                WLFR_RESERVE_AMT        1944661        96.560938
13           WLFR_RET_OTH_COST_AMT        1943077        96.482285
14             WLFR_UNPAID_DUE_AMT        1929725        95.819300
15          WLFR_RET_OTH_CHRGS_AMT        1927076        95.687765
16      INS_FAIL_PROVIDE_INFO_TEXT        1925535        95.611248
17        WLFR_RET_OTH_EXPENSE_AMT        1922276        95.449424
18         WLFR_CLAIMS_RESERVE_AMT        1915721        95.123940
19            PENSION_OTH_DED_TEXT        1913795        95.028305
20              WLFR_RET_TAXES_AMT        1909472        94.813650
21            WLFR_RET_CHARGES_AMT        1906190        94.650684
22        PENSION_DIVND_CR_DEP_AMT        1906187        94.650535
23           WLFR_INCR_RESERVE_AMT        1902569        94.470885
24           WLFR_CLAIMS_CHRGD_AMT        1900251        94.355787
25              WLFR_RET_ADMIN_AMT        1895846        94.137059
26        WLFR_RET_COMMISSIONS_AMT        1891730        93.932682
27              PENSION_OTHER_TEXT        1879846        93.342589
28    UNALLOC_CONTRACTS_OTHER_TEXT        1877483        93.225256
29         PENSION_TRANSFER_TO_AMT        1873821        93.043421
30            WLFR_CLAIMS_PAID_AMT        1873730        93.038903
31             PENSION_OTH_DED_AMT        1873479        93.026439
32       PENSION_TRANSFER_FROM_AMT        1869123        92.810145
33           WLFR_PREMIUM_RCVD_AMT        1856161        92.166525
34               PENSION_OTHER_AMT        1850660        91.893376
35          PENSION_ADMIN_CHRG_AMT        1842787        91.502447
36         PENSION_CONTRIB_DEP_AMT        1829854        90.860267
37        PENSION_BNFTS_DSBRSD_AMT        1825054        90.621926
38       PENSION_INT_CR_DUR_YR_AMT        1806300        89.690708
39        PENSION_EOY_SEP_ACCT_AMT        1801810        89.467760
40        PENSION_EOY_GEN_ACCT_AMT        1798125        89.284783
41         WLFR_TYPE_BNFT_OTH_TEXT        1334931        66.285172
42        PENSION_END_PREV_BAL_AMT        1135344        56.374803
43         WLFR_INCURRED_CLAIM_AMT         941677        46.758388
44                WLFR_RET_TOT_AMT         939366        46.643637
45        PENSION_TOT_BAL_ADDN_AMT         897981        44.588690
46        WLFR_TOT_EARNED_PREM_AMT         861460        42.775263
47             PENSION_TOT_DED_AMT         840382        41.728648
48       PENSION_TOT_ADDITIONS_AMT         837718        41.596368
49             PENSION_EOY_BAL_AMT         821774        40.804679
50       ALLOC_CONTRACTS_GROUP_IND         690503        34.286499
51       ALLOC_CONTRACTS_OTHER_IND         688449        34.184509
52       ALLOC_CONTRACTS_INDIV_IND         686615        34.093443
53  UNAL_CONTRAC_IMM_PART_GUAR_IND         686320        34.078795
54   UNALLOC_CONTRACTS_DEP_ADM_IND         682634        33.895769
55  UNAL_CONTRACTS_GUAR_INVEST_IND         672528        33.393961
56            WLFR_REFUND_CASH_IND         659802        32.762060
57          WLFR_REFUND_CREDIT_IND         659646        32.754314
58    PENS_DISTR_BNFT_TERM_PLN_IND         653608        32.454500
59     UNALLOC_CONTRACTS_OTHER_IND         645101        32.032091
60         WLFR_BNFT_STOP_LOSS_IND         604309        30.006589
61             WLFR_BNFT_UNEMP_IND         584827        29.039222
62         WLFR_BNFT_INDEMNITY_IND         565214        28.065351
63               WLFR_BNFT_HMO_IND         553377        27.477592
64               WLFR_BNFT_PPO_IND         550517        27.335581
65        WLFR_BNFT_TEMP_DISAB_IND         520109        25.825690
66   WLFR_BNFT_LONG_TERM_DISAB_IND         508396        25.244089
67              WLFR_BNFT_DRUG_IND         501283        24.890897
68            WLFR_BNFT_DENTAL_IND         476154        23.643132
69            WLFR_BNFT_VISION_IND         471046        23.389497
70            WLFR_BNFT_HEALTH_IND         467363        23.206620
71        WLFR_BNFT_LIFE_INSUR_IND         466142        23.145992
72       WLFR_TOT_CHARGES_PAID_AMT         410547        20.385457
73             WLFR_BNFT_OTHER_IND         407595        20.238877
74         INS_BROKER_FEES_TOT_AMT         360592        17.904972
75         INS_BROKER_COMM_TOT_AMT         292837        14.540640
76       INS_FAIL_PROVIDE_INFO_IND          44095         2.189510
77        INS_PRSN_COVERED_EOY_CNT          26927         1.337044
78           INS_CARRIER_NAIC_CODE           9491         0.471270
79                INS_CONTRACT_NUM           8416         0.417891
80            INS_POLICY_FROM_DATE           8117         0.403045
81              INS_POLICY_TO_DATE           5865         0.291223
82                 INS_CARRIER_EIN           5084         0.252443
83                INS_CARRIER_NAME           1001         0.049704