# Innovation Summit 2026 Exploratory Data Analysis: Form 5500 - Schedule C Part 1, Item 2

This is a notebook of exploratory data analysis, made by Corey Michaud, for the Deloitte Innovation Summit 2026 Competition as a part of the Data Atlas team.

## Libraries

In [1]:
# Libraries
import pandas as pd
import duckdb
from innovation_summit.config import DB_PATH

In [2]:
# Displaying all
pd.set_option("display.max_rows", None)

## Load Form 5500 - Schedule C Part 1, Item 2 data

In [3]:
# Loading data
with duckdb.connect(DB_PATH, read_only=True) as con:
    SCH_C_P1_I2 = con.sql("SELECT * FROM silver.SCH_C_P1_I2").df()

## Viewing data

In [4]:
# Head of SCH_C_P1_I2
SCH_C_P1_I2.head()

,ACK_ID,PROVIDER_OTHER_AMT_FORMULA_IND,PROVIDER_OTHER_DIRECT_COMP_AMT,PROVIDER_OTHER_EIN,PROVIDER_OTHER_NAME,PROVIDER_OTHER_RELATION,PROVIDER_OTHER_SRVC_CODES,PROVIDER_OTHER_US_ADDRESS1,PROVIDER_OTHER_US_ADDRESS2,PROVIDER_OTHER_US_CITY,...,PROV_OTHER_FOREIGN_ADDRESS1,PROV_OTHER_FOREIGN_ADDRESS2,PROV_OTHER_FOREIGN_CITY,PROV_OTHER_FOREIGN_CNTRY,PROV_OTHER_FOREIGN_POSTAL_CD,PROV_OTHER_FOREIGN_PROV_STATE,PROV_OTHER_INDIRECT_COMP_IND,PROV_OTHER_TOT_IND_COMP_AMT,ROW_ORDER,FORM_YEAR
0,20200720121624NAL0000978001001,2,0.0,NaN,HUB INTERNATIONAL OF ILLINOIS LTD,BROKER,None,55 E JACKSON BLVD FL 12,NaN,CHICAGO,...,NaN,NaN,NaN,NaN,NaN,NaN,1,8160.0,4.0,2019
1,20200720121624NAL0000978001001,NaN,8056.0,232614764,CAREBRIDGE CORPORATION,CONTRACT ADMINISTRATORS,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,5.0,2019
2,20200720121725NAL0001062131001,1,29113.0,840467907,GREAT-WEST LIFE & ANNUITY INSURANCE,RECORDKEEPER,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,0.0,1.0,2019
3,20200720122157NAL0001065651001,1,992.0,010233346,JOHN HANCOCK LIFE INSURANCE COMPANY,RECORDKEEPER,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,0.0,1.0,2019
4,20200720122209NAL0001706226003,2,765329.0,391995276,"UMR, INC.",CLAIMS PROCESSING,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,11943.0,1.0,2019

## Shape of data

In [5]:
# Shape
print(f"Rows: {SCH_C_P1_I2.shape[0]}\nColumns: {SCH_C_P1_I2.shape[1]}")

Rows: 1673300
Columns: 23

## Data types

In [6]:
# Data type counts
SCH_C_P1_I2.dtypes.value_counts()

str        18
float64     3
object      1
int32       1
Name: count, dtype: int64

## Any missing data?

In [7]:
# Columns with no missing data
SCH_C_P1_I2.isna().sum()[SCH_C_P1_I2.isna().sum() == 0]

ACK_ID       0
ROW_ORDER    0
FORM_YEAR    0
dtype: int64

In [8]:
# Missing data
pd.DataFrame(
    {
        "missing_count": SCH_C_P1_I2.isna().sum(),
        "missing_percent": SCH_C_P1_I2.isna().mean().mul(100),
    }
).query("missing_count > 0").sort_values(
    "missing_percent", ascending=False
).rename_axis("column_name").reset_index()

                       column_name  missing_count  missing_percent
0        PROVIDER_OTHER_SRVC_CODES        1673300       100.000000
1      PROV_OTHER_FOREIGN_ADDRESS2        1671221        99.875754
2    PROV_OTHER_FOREIGN_PROV_STATE        1668681        99.723959
3     PROV_OTHER_FOREIGN_POSTAL_CD        1668477        99.711767
4      PROV_OTHER_FOREIGN_ADDRESS1        1668118        99.690313
5         PROV_OTHER_FOREIGN_CNTRY        1668118        99.690313
6          PROV_OTHER_FOREIGN_CITY        1668118        99.690313
7       PROVIDER_OTHER_US_ADDRESS2        1597624        95.477440
8            PROVIDER_OTHER_US_ZIP        1236948        73.922668
9       PROVIDER_OTHER_US_ADDRESS1        1236948        73.922668
10          PROVIDER_OTHER_US_CITY        1236948        73.922668
11         PROVIDER_OTHER_US_STATE        1236948        73.922668
12  PROVIDER_OTHER_AMT_FORMULA_IND         937959        56.054443
13     PROV_OTHER_TOT_IND_COMP_AMT         926477        55.368254
14    PROV_OTHER_ELIG_IND_COMP_IND         909947        54.380386
15              PROVIDER_OTHER_EIN         294453        17.597143
16         PROVIDER_OTHER_RELATION          26918         1.608677
17    PROV_OTHER_INDIRECT_COMP_IND          15606         0.932648
18  PROVIDER_OTHER_DIRECT_COMP_AMT           9758         0.583159
19             PROVIDER_OTHER_NAME            883         0.052770