# Innovation Summit 2026 Exploratory Data Analysis: Form 5500 - Schedule C Part 1, Item 2

This is a notebook of exploratory data analysis, made by Corey Michaud, for the Deloitte Innovation Summit 2026 Competition as a part of the Data Atlas team.

## Libraries

In [1]:
# Libraries
import pandas as pd
from innovation_summit.config import COMBINED_DATA_PATH

In [2]:
# Displaying all
pd.set_option("display.max_rows", None)

## Load Form 5500 - Schedule C Part 1, Item 2 data

In [3]:
# Loading data
SCH_C_P1_I2 = pd.read_parquet(COMBINED_DATA_PATH / "SCH_C_P1_I2.parquet")

## Viewing data

In [4]:
# Head of SCH_C_P1_I2
SCH_C_P1_I2.head()

,ACK_ID,ROW_ORDER,PROVIDER_OTHER_NAME,PROVIDER_OTHER_EIN,PROVIDER_OTHER_US_ADDRESS1,PROVIDER_OTHER_US_ADDRESS2,PROVIDER_OTHER_US_CITY,PROVIDER_OTHER_US_STATE,PROVIDER_OTHER_US_ZIP,PROV_OTHER_FOREIGN_ADDRESS1,...,PROV_OTHER_FOREIGN_CNTRY,PROV_OTHER_FOREIGN_POSTAL_CD,PROVIDER_OTHER_SRVC_CODES,PROVIDER_OTHER_RELATION,PROVIDER_OTHER_DIRECT_COMP_AMT,PROV_OTHER_INDIRECT_COMP_IND,PROV_OTHER_ELIG_IND_COMP_IND,PROV_OTHER_TOT_IND_COMP_AMT,PROVIDER_OTHER_AMT_FORMULA_IND,FORM_YEAR
0,20200720121624NAL0000978001001,4.0,HUB INTERNATIONAL OF ILLINOIS LTD,<NA>,55 E JACKSON BLVD FL 12,<NA>,CHICAGO,IL,60604,<NA>,...,<NA>,<NA>,<NA>,BROKER,0.0,1,2,8160.0,2,2019
1,20200720121624NAL0000978001001,5.0,CAREBRIDGE CORPORATION,232614764,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,CONTRACT ADMINISTRATORS,8056.0,2,<NA>,<NA>,<NA>,2019
2,20200720121725NAL0001062131001,1.0,GREAT-WEST LIFE & ANNUITY INSURANCE,840467907,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,RECORDKEEPER,29113.0,1,1,0.0,1,2019
3,20200720122157NAL0001065651001,1.0,JOHN HANCOCK LIFE INSURANCE COMPANY,010233346,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,RECORDKEEPER,992.0,1,1,0.0,1,2019
4,20200720122209NAL0001706226003,1.0,"UMR, INC.",391995276,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,CLAIMS PROCESSING,765329.0,1,2,11943.0,2,2019

## Shape of data

In [5]:
# Shape
print(f"Rows: {SCH_C_P1_I2.shape[0]}\nColumns: {SCH_C_P1_I2.shape[1]}")

Rows: 1673300
Columns: 23

## Data types

In [6]:
# Data type counts
SCH_C_P1_I2.dtypes.value_counts()

string     19
Float64     3
str         1
Name: count, dtype: int64

## Any missing data?

In [7]:
# Columns with no missing data
SCH_C_P1_I2.isna().sum()[SCH_C_P1_I2.isna().sum() == 0]

ACK_ID       0
ROW_ORDER    0
FORM_YEAR    0
dtype: int64

In [8]:
# Missing data
pd.DataFrame({
    "missing_count": SCH_C_P1_I2.isna().sum(),
    "missing_percent": SCH_C_P1_I2.isna().mean().mul(100)
}).query("missing_count > 0").sort_values("missing_percent", ascending=False).rename_axis("column_name").reset_index()

                       column_name  missing_count  missing_percent
0        PROVIDER_OTHER_SRVC_CODES        1673300       100.000000
1      PROV_OTHER_FOREIGN_ADDRESS2        1671224        99.875934
2    PROV_OTHER_FOREIGN_PROV_STATE        1668681        99.723959
3     PROV_OTHER_FOREIGN_POSTAL_CD        1668477        99.711767
4         PROV_OTHER_FOREIGN_CNTRY        1668127        99.690850
5      PROV_OTHER_FOREIGN_ADDRESS1        1668118        99.690313
6          PROV_OTHER_FOREIGN_CITY        1668118        99.690313
7       PROVIDER_OTHER_US_ADDRESS2        1597636        95.478157
8       PROVIDER_OTHER_US_ADDRESS1        1236954        73.923026
9           PROVIDER_OTHER_US_CITY        1236949        73.922728
10         PROVIDER_OTHER_US_STATE        1236948        73.922668
11           PROVIDER_OTHER_US_ZIP        1236948        73.922668
12  PROVIDER_OTHER_AMT_FORMULA_IND         937959        56.054443
13     PROV_OTHER_TOT_IND_COMP_AMT         926477        55.368254
14    PROV_OTHER_ELIG_IND_COMP_IND         909947        54.380386
15              PROVIDER_OTHER_EIN         294453        17.597143
16         PROVIDER_OTHER_RELATION          44559         2.662941
17    PROV_OTHER_INDIRECT_COMP_IND          15606         0.932648
18  PROVIDER_OTHER_DIRECT_COMP_AMT           9758         0.583159
19             PROVIDER_OTHER_NAME            892         0.053308