# Benefits Market Intelligence Exploratory Data Analysis: Form 5500 - Schedule C Part 1, Item 2

## Libraries

In [10]:
# Libraries
import pandas as pd
import duckdb
from benefits_market_intelligence.config.paths import DB_PATH

In [11]:
# Displaying all
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

## Load Form 5500 - Schedule C Part 1, Item 2 data

In [12]:
# Loading data
with duckdb.connect(DB_PATH, read_only=True) as con:
    SCH_C_P1_I2 = con.sql("SELECT * FROM silver.SCH_C_P1_I2").df()

In [13]:
# Convert pandas-made object columns to string
obj_cols = SCH_C_P1_I2.dtypes[SCH_C_P1_I2.dtypes == "object"].index
SCH_C_P1_I2[obj_cols] = SCH_C_P1_I2[obj_cols].astype("str")

## Viewing data

In [14]:
# Head of SCH_C_P1_I2
SCH_C_P1_I2.head()

,ACK_ID,PROVIDER_OTHER_AMT_FORMULA_IND,PROVIDER_OTHER_DIRECT_COMP_AMT,PROVIDER_OTHER_EIN,PROVIDER_OTHER_NAME,PROVIDER_OTHER_RELATION,PROVIDER_OTHER_SRVC_CODES,PROVIDER_OTHER_US_ADDRESS1,PROVIDER_OTHER_US_ADDRESS2,PROVIDER_OTHER_US_CITY,PROVIDER_OTHER_US_STATE,PROVIDER_OTHER_US_ZIP,PROV_OTHER_ELIG_IND_COMP_IND,PROV_OTHER_FOREIGN_ADDRESS1,PROV_OTHER_FOREIGN_ADDRESS2,PROV_OTHER_FOREIGN_CITY,PROV_OTHER_FOREIGN_CNTRY,PROV_OTHER_FOREIGN_POSTAL_CD,PROV_OTHER_FOREIGN_PROV_STATE,PROV_OTHER_INDIRECT_COMP_IND,PROV_OTHER_TOT_IND_COMP_AMT,ROW_ORDER,FORM_YEAR
0,20200720121624NAL0000978001001,2,0.0,NaN,HUB INTERNATIONAL OF ILLINOIS LTD,BROKER,NaN,55 E JACKSON BLVD FL 12,NaN,CHICAGO,IL,60604,2,NaN,NaN,NaN,NaN,NaN,NaN,1,8160.0,4.0,2019
1,20200720121624NAL0000978001001,NaN,8056.0,232614764,CAREBRIDGE CORPORATION,CONTRACT ADMINISTRATORS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,5.0,2019
2,20200720121725NAL0001062131001,1,29113.0,840467907,GREAT-WEST LIFE & ANNUITY INSURANCE,RECORDKEEPER,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,1,0.0,1.0,2019
3,20200720122157NAL0001065651001,1,992.0,010233346,JOHN HANCOCK LIFE INSURANCE COMPANY,RECORDKEEPER,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,1,0.0,1.0,2019
4,20200720122209NAL0001706226003,2,765329.0,391995276,"UMR, INC.",CLAIMS PROCESSING,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,1,11943.0,1.0,2019

## Shape of data

In [15]:
# Shape
print(f"Rows: {SCH_C_P1_I2.shape[0]}\nColumns: {SCH_C_P1_I2.shape[1]}")

Rows: 1675037
Columns: 23

## Data types

In [16]:
# Data type counts
SCH_C_P1_I2.dtypes.value_counts()

str        19
float64     3
int32       1
Name: count, dtype: int64

## Any missing data?

In [17]:
# Columns with no missing data
SCH_C_P1_I2.isna().sum()[SCH_C_P1_I2.isna().sum() == 0]

ACK_ID       0
ROW_ORDER    0
FORM_YEAR    0
dtype: int64

In [18]:
# Missing data
pd.DataFrame(
    {
        "missing_count": SCH_C_P1_I2.isna().sum(),
        "missing_percent": SCH_C_P1_I2.isna().mean().mul(100),
    }
).query("missing_count > 0").sort_values(
    "missing_percent", ascending=False
).rename_axis("column_name").reset_index()

                       column_name  missing_count  missing_percent
0        PROVIDER_OTHER_SRVC_CODES        1675037       100.000000
1      PROV_OTHER_FOREIGN_ADDRESS2        1672957        99.875824
2    PROV_OTHER_FOREIGN_PROV_STATE        1670417        99.724185
3     PROV_OTHER_FOREIGN_POSTAL_CD        1670213        99.712006
4      PROV_OTHER_FOREIGN_ADDRESS1        1669854        99.690574
5         PROV_OTHER_FOREIGN_CNTRY        1669854        99.690574
6          PROV_OTHER_FOREIGN_CITY        1669854        99.690574
7       PROVIDER_OTHER_US_ADDRESS2        1599283        95.477473
8            PROVIDER_OTHER_US_ZIP        1238137        73.916994
9       PROVIDER_OTHER_US_ADDRESS1        1238137        73.916994
10          PROVIDER_OTHER_US_CITY        1238137        73.916994
11         PROVIDER_OTHER_US_STATE        1238137        73.916994
12  PROVIDER_OTHER_AMT_FORMULA_IND         939241        56.072851
13     PROV_OTHER_TOT_IND_COMP_AMT         927721        55.385105
14    PROV_OTHER_ELIG_IND_COMP_IND         911210        54.399395
15              PROVIDER_OTHER_EIN         294797        17.599432
16         PROVIDER_OTHER_RELATION          26961         1.609576
17    PROV_OTHER_INDIRECT_COMP_IND          15623         0.932696
18  PROVIDER_OTHER_DIRECT_COMP_AMT           9764         0.582912
19             PROVIDER_OTHER_NAME            883         0.052715