# Benefits Market Intelligence Exploratory Data Analysis: Form 5500 - Schedule A

## Libraries

In [1]:
# Libraries
import pandas as pd
import duckdb
from benefits_market_intelligence.config.paths import DB_PATH

In [2]:
# Displaying all
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

## Load Form 5500 - Schedule A data

In [3]:
# Loading data
with duckdb.connect(DB_PATH, read_only=True) as con:
    SCH_A = con.sql("SELECT * FROM silver.SCH_A").df()

## Viewing data

In [5]:
# Head of SCH_A
SCH_A.head()

,ACK_ID,ALLOC_CONTRACTS_GROUP_IND,ALLOC_CONTRACTS_INDIV_IND,ALLOC_CONTRACTS_OTHER_IND,ALLOC_CONTRACTS_OTHER_TEXT,FORM_ID,INS_BROKER_COMM_TOT_AMT,INS_BROKER_FEES_TOT_AMT,INS_CARRIER_EIN,INS_CARRIER_NAIC_CODE,INS_CARRIER_NAME,INS_CONTRACT_NUM,INS_FAIL_PROVIDE_INFO_IND,INS_FAIL_PROVIDE_INFO_TEXT,INS_POLICY_FROM_DATE,INS_POLICY_TO_DATE,INS_PRSN_COVERED_EOY_CNT,PENSION_ADMIN_CHRG_AMT,PENSION_BASIS_RATES_TEXT,PENSION_BNFTS_DSBRSD_AMT,PENSION_CONTRACT_COST_AMT,PENSION_CONTRIB_DEP_AMT,PENSION_COST_TEXT,PENSION_DIVND_CR_DEP_AMT,PENSION_END_PREV_BAL_AMT,PENSION_EOY_BAL_AMT,PENSION_EOY_GEN_ACCT_AMT,PENSION_EOY_SEP_ACCT_AMT,PENSION_INT_CR_DUR_YR_AMT,PENSION_OTHER_AMT,PENSION_OTHER_TEXT,PENSION_OTH_DED_AMT,PENSION_OTH_DED_TEXT,PENSION_PREM_PAID_TOT_AMT,PENSION_TOT_ADDITIONS_AMT,PENSION_TOT_BAL_ADDN_AMT,PENSION_TOT_DED_AMT,PENSION_TRANSFER_FROM_AMT,PENSION_TRANSFER_TO_AMT,PENSION_UNPAID_PREMIUM_AMT,PENS_DISTR_BNFT_TERM_PLN_IND,SCH_A_EIN,SCH_A_PLAN_NUM,SCH_A_PLAN_YEAR_BEGIN_DATE,SCH_A_PLAN_YEAR_END_DATE,UNALLOC_CONTRACTS_DEP_ADM_IND,UNALLOC_CONTRACTS_OTHER_IND,UNALLOC_CONTRACTS_OTHER_TEXT,UNAL_CONTRACTS_GUAR_INVEST_IND,UNAL_CONTRAC_IMM_PART_GUAR_IND,WLFR_ACQUIS_COST_AMT,WLFR_ACQUIS_COST_TEXT,WLFR_BNFT_DENTAL_IND,WLFR_BNFT_DRUG_IND,WLFR_BNFT_HEALTH_IND,WLFR_BNFT_HMO_IND,WLFR_BNFT_INDEMNITY_IND,WLFR_BNFT_LIFE_INSUR_IND,WLFR_BNFT_LONG_TERM_DISAB_IND,WLFR_BNFT_OTHER_IND,WLFR_BNFT_PPO_IND,WLFR_BNFT_STOP_LOSS_IND,WLFR_BNFT_TEMP_DISAB_IND,WLFR_BNFT_UNEMP_IND,WLFR_BNFT_VISION_IND,WLFR_CLAIMS_CHRGD_AMT,WLFR_CLAIMS_PAID_AMT,WLFR_CLAIMS_RESERVE_AMT,WLFR_DIVNDS_DUE_AMT,WLFR_HELD_BNFTS_AMT,WLFR_INCR_RESERVE_AMT,WLFR_INCURRED_CLAIM_AMT,WLFR_OTH_RESERVE_AMT,WLFR_PREMIUM_RCVD_AMT,WLFR_REFUND_AMT,WLFR_REFUND_CASH_IND,WLFR_REFUND_CREDIT_IND,WLFR_RESERVE_AMT,WLFR_RET_ADMIN_AMT,WLFR_RET_CHARGES_AMT,WLFR_RET_COMMISSIONS_AMT,WLFR_RET_OTH_CHRGS_AMT,WLFR_RET_OTH_COST_AMT,WLFR_RET_OTH_EXPENSE_AMT,WLFR_RET_TAXES_AMT,WLFR_RET_TOT_AMT,WLFR_TOT_CHARGES_PAID_AMT,WLFR_TOT_EARNED_PREM_AMT,WLFR_TYPE_BNFT_OTH_TEXT,WLFR_UNPAID_DUE_AMT,FORM_YEAR
0,20200407140313NAL0005903843001,NaN,NaN,NaN,NaN,1.0,NaN,NaN,470098400,61301,AMERITAS LIFE INSURANCE CO.,E23 0351,NaN,NaN,2019-01-01,2019-12-31,67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1881317.0,1881317.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1881317.0,NaN,NaN,NaN,NaN,NaN,746141016,001,2019-01-01,2019-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019
1,20200408103626NAL0010330753001,0,0,0,NaN,1.0,4751.0,429.0,710505232,94358,USABLE LIFE,50003755,2,NaN,2013-11-01,2014-10-31,236,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0,620648833,502,2013-11-01,2014-10-31,0,0,NaN,0,0,NaN,NaN,0,0,0,0,0,1,0,1,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,21442.0,0.0,"AD&D, SUPPLEMENTAL/DEPENDENT LIFE",NaN,2019
2,20200408103626NAL0010330753001,0,0,0,NaN,2.0,2457.0,222.0,710505232,94358,USABLE LIFE,50003755,2,NaN,2013-11-01,2014-10-31,236,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0,620648833,502,2013-11-01,2014-10-31,0,0,NaN,0,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,11101.0,0.0,NaN,NaN,2019
3,20200408103709NAL0014724896001,0,0,0,NaN,1.0,3914.0,429.0,710505232,94358,USABLE LIFE,50003755,2,NaN,2014-11-01,2015-10-31,250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0,620648833,502,2014-11-01,2015-10-31,0,0,NaN,0,0,NaN,NaN,0,0,0,0,0,1,0,1,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,21448.0,0.0,"AD&D, SUPPLEMENTAL/DEPENDENT LIFE",NaN,2019
4,20200408103709NAL0014724896001,0,0,0,NaN,2.0,2144.0,237.0,710505232,94358,USABLE LIFE,50003755,2,NaN,2014-11-01,2015-10-31,250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0,620648833,502,2014-11-01,2015-10-31,0,0,NaN,0,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,11845.0,0.0,NaN,NaN,2019

## Shape of data

In [6]:
# Shape
print(f"Rows: {SCH_A.shape[0]}\nColumns: {SCH_A.shape[1]}")

Rows: 2015924
Columns: 91

## Data types

In [7]:
# Data type counts
SCH_A.dtypes.value_counts()

float64           45
str               41
datetime64[us]     4
int32              1
Name: count, dtype: int64

## Any missing data?

In [8]:
# Columns with no missing data
SCH_A.isna().sum()[SCH_A.isna().sum() == 0]

ACK_ID                        0
FORM_ID                       0
SCH_A_EIN                     0
SCH_A_PLAN_NUM                0
SCH_A_PLAN_YEAR_BEGIN_DATE    0
SCH_A_PLAN_YEAR_END_DATE      0
FORM_YEAR                     0
dtype: int64

In [9]:
# Missing data
pd.DataFrame(
    {
        "missing_count": SCH_A.isna().sum(),
        "missing_percent": SCH_A.isna().mean().mul(100),
    }
).query("missing_count > 0").sort_values(
    "missing_percent", ascending=False
).rename_axis("column_name").reset_index()

                       column_name  missing_count  missing_percent
0                PENSION_COST_TEXT        2014813        99.944889
1       ALLOC_CONTRACTS_OTHER_TEXT        2011780        99.794437
2        PENSION_CONTRACT_COST_AMT        2010040        99.708124
3       PENSION_UNPAID_PREMIUM_AMT        2006977        99.556184
4        PENSION_PREM_PAID_TOT_AMT        1999751        99.197738
5         PENSION_BASIS_RATES_TEXT        1997956        99.108697
6            WLFR_ACQUIS_COST_TEXT        1970779        97.760580
7             WLFR_ACQUIS_COST_AMT        1956105        97.032676
8              WLFR_DIVNDS_DUE_AMT        1954944        96.975084
9              WLFR_HELD_BNFTS_AMT        1954117        96.934061
10            WLFR_OTH_RESERVE_AMT        1953154        96.886291
11                 WLFR_REFUND_AMT        1949665        96.713219
12                WLFR_RESERVE_AMT        1946581        96.560237
13           WLFR_RET_OTH_COST_AMT        1945010        96.482308
14             WLFR_UNPAID_DUE_AMT        1931625        95.818344
15          WLFR_RET_OTH_CHRGS_AMT        1928980        95.687139
16      INS_FAIL_PROVIDE_INFO_TEXT        1927415        95.609507
17        WLFR_RET_OTH_EXPENSE_AMT        1924139        95.447001
18         WLFR_CLAIMS_RESERVE_AMT        1917586        95.121939
19            PENSION_OTH_DED_TEXT        1915762        95.031460
20              WLFR_RET_TAXES_AMT        1911318        94.811015
21        PENSION_DIVND_CR_DEP_AMT        1908177        94.655205
22            WLFR_RET_CHARGES_AMT        1908037        94.648261
23           WLFR_INCR_RESERVE_AMT        1904423        94.468988
24           WLFR_CLAIMS_CHRGD_AMT        1902097        94.353607
25              WLFR_RET_ADMIN_AMT        1897734        94.137180
26        WLFR_RET_COMMISSIONS_AMT        1893550        93.929632
27              PENSION_OTHER_TEXT        1881800        93.346773
28    UNALLOC_CONTRACTS_OTHER_TEXT        1879416        93.228515
29         PENSION_TRANSFER_TO_AMT        1875797        93.048994
30            WLFR_CLAIMS_PAID_AMT        1875554        93.036940
31             PENSION_OTH_DED_AMT        1875459        93.032227
32       PENSION_TRANSFER_FROM_AMT        1871101        92.816049
33           WLFR_PREMIUM_RCVD_AMT        1857955        92.163941
34               PENSION_OTHER_AMT        1852627        91.899645
35          PENSION_ADMIN_CHRG_AMT        1844743        91.508559
36         PENSION_CONTRIB_DEP_AMT        1831806        90.866818
37        PENSION_BNFTS_DSBRSD_AMT        1827001        90.628466
38       PENSION_INT_CR_DUR_YR_AMT        1808244        89.698024
39        PENSION_EOY_SEP_ACCT_AMT        1803721        89.473661
40        PENSION_EOY_GEN_ACCT_AMT        1800039        89.291015
41         WLFR_TYPE_BNFT_OTH_TEXT        1336217        66.283104
42        PENSION_END_PREV_BAL_AMT        1136858        56.393892
43         WLFR_INCURRED_CLAIM_AMT         942721        46.763717
44                WLFR_RET_TOT_AMT         940408        46.648981
45        PENSION_TOT_BAL_ADDN_AMT         899135        44.601632
46        WLFR_TOT_EARNED_PREM_AMT         862417        42.780234
47             PENSION_TOT_DED_AMT         841399        41.737635
48       PENSION_TOT_ADDITIONS_AMT         838729        41.605189
49             PENSION_EOY_BAL_AMT         822804        40.815229
50       ALLOC_CONTRACTS_GROUP_IND         691303        34.292116
51       ALLOC_CONTRACTS_OTHER_IND         689248        34.190178
52       ALLOC_CONTRACTS_INDIV_IND         687412        34.099103
53  UNAL_CONTRAC_IMM_PART_GUAR_IND         687119        34.084569
54   UNALLOC_CONTRACTS_DEP_ADM_IND         683432        33.901675
55  UNAL_CONTRACTS_GUAR_INVEST_IND         673323        33.400217
56            WLFR_REFUND_CASH_IND         660566        32.767406
57          WLFR_REFUND_CREDIT_IND         660410        32.759668
58    PENS_DISTR_BNFT_TERM_PLN_IND         654362        32.459656
59     UNALLOC_CONTRACTS_OTHER_IND         645880        32.038906
60         WLFR_BNFT_STOP_LOSS_IND         605021        30.012094
61             WLFR_BNFT_UNEMP_IND         585526        29.045043
62         WLFR_BNFT_INDEMNITY_IND         565893        28.071148
63               WLFR_BNFT_HMO_IND         554036        27.482981
64               WLFR_BNFT_PPO_IND         551156        27.340118
65        WLFR_BNFT_TEMP_DISAB_IND         520729        25.830785
66   WLFR_BNFT_LONG_TERM_DISAB_IND         509004        25.249166
67              WLFR_BNFT_DRUG_IND         501879        24.895730
68            WLFR_BNFT_DENTAL_IND         476689        23.646179
69            WLFR_BNFT_VISION_IND         471594        23.393441
70            WLFR_BNFT_HEALTH_IND         467890        23.209704
71        WLFR_BNFT_LIFE_INSUR_IND         466686        23.149980
72       WLFR_TOT_CHARGES_PAID_AMT         410858        20.380629
73             WLFR_BNFT_OTHER_IND         408080        20.242827
74         INS_BROKER_FEES_TOT_AMT         360955        17.905189
75         INS_BROKER_COMM_TOT_AMT         293026        14.535568
76       INS_FAIL_PROVIDE_INFO_IND          44136         2.189368
77        INS_PRSN_COVERED_EOY_CNT          26925         1.335616
78           INS_CARRIER_NAIC_CODE           9500         0.471248
79                INS_CONTRACT_NUM           8424         0.417873
80            INS_POLICY_FROM_DATE           8115         0.402545
81              INS_POLICY_TO_DATE           5862         0.290785
82                 INS_CARRIER_EIN           5086         0.252291
83                INS_CARRIER_NAME            999         0.049555

# Average ins_broker_fees_tot_amt by Year

In [10]:
SCH_A.groupby("FORM_YEAR")["INS_BROKER_FEES_TOT_AMT"].mean().round(3)

FORM_YEAR
2019       6732.425
2020       8648.135
2021       6243.368
2022      22599.782
2023    4746876.097
2024     286934.258
Name: INS_BROKER_FEES_TOT_AMT, dtype: float64